// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-grapql-service/internal/usecase.CommentRepository -o comment_repository_mock.go -n CommentRepositoryMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-grapql-service/internal/model"
)

// CommentRepositoryMock implements mm_usecase.CommentRepository
type CommentRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, comment model.Comment) (c2 model.Comment, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, comment model.Comment)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mCommentRepositoryMockCreate

	funcGetByID          func(ctx context.Context, id int64) (c2 model.Comment, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id int64)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mCommentRepositoryMockGetByID

	funcListByPostAndParent          func(ctx context.Context, filter model.CommentListFilter) (ca1 []model.Comment, b1 bool, err error)
	funcListByPostAndParentOrigin    string
	inspectFuncListByPostAndParent   func(ctx context.Context, filter model.CommentListFilter)
	afterListByPostAndParentCounter  uint64
	beforeListByPostAndParentCounter uint64
	ListByPostAndParentMock          mCommentRepositoryMockListByPostAndParent
}

// NewCommentRepositoryMock returns a mock for mm_usecase.CommentRepository
func NewCommentRepositoryMock(t minimock.Tester) *CommentRepositoryMock {
	m := &CommentRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mCommentRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*CommentRepositoryMockCreateParams{}

	m.GetByIDMock = mCommentRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*CommentRepositoryMockGetByIDParams{}

	m.ListByPostAndParentMock = mCommentRepositoryMockListByPostAndParent{mock: m}
	m.ListByPostAndParentMock.callArgs = []*CommentRepositoryMockListByPostAndParentParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCommentRepositoryMockCreate struct {
	optional           bool
	mock               *CommentRepositoryMock
	defaultExpectation *CommentRepositoryMockCreateExpectation
	expectations       []*CommentRepositoryMockCreateExpectation

	callArgs []*CommentRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentRepositoryMockCreateExpectation specifies expectation struct of the CommentRepository.Create
type CommentRepositoryMockCreateExpectation struct {
	mock               *CommentRepositoryMock
	params             *CommentRepositoryMockCreateParams
	paramPtrs          *CommentRepositoryMockCreateParamPtrs
	expectationOrigins CommentRepositoryMockCreateExpectationOrigins
	results            *CommentRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// CommentRepositoryMockCreateParams contains parameters of the CommentRepository.Create
type CommentRepositoryMockCreateParams struct {
	ctx     context.Context
	comment model.Comment
}

// CommentRepositoryMockCreateParamPtrs contains pointers to parameters of the CommentRepository.Create
type CommentRepositoryMockCreateParamPtrs struct {
	ctx     *context.Context
	comment *model.Comment
}

// CommentRepositoryMockCreateResults contains results of the CommentRepository.Create
type CommentRepositoryMockCreateResults struct {
	c2  model.Comment
	err error
}

// CommentRepositoryMockCreateOrigins contains origins of expectations of the CommentRepository.Create
type CommentRepositoryMockCreateExpectationOrigins struct {
	origin        string
	originCtx     string
	originComment string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mCommentRepositoryMockCreate) Optional() *mCommentRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for CommentRepository.Create
func (mmCreate *mCommentRepositoryMockCreate) Expect(ctx context.Context, comment model.Comment) *mCommentRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &CommentRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &CommentRepositoryMockCreateParams{ctx, comment}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for CommentRepository.Create
func (mmCreate *mCommentRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mCommentRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &CommentRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &CommentRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectCommentParam2 sets up expected param comment for CommentRepository.Create
func (mmCreate *mCommentRepositoryMockCreate) ExpectCommentParam2(comment model.Comment) *mCommentRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &CommentRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &CommentRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.comment = &comment
	mmCreate.defaultExpectation.expectationOrigins.originComment = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the CommentRepository.Create
func (mmCreate *mCommentRepositoryMockCreate) Inspect(f func(ctx context.Context, comment model.Comment)) *mCommentRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for CommentRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by CommentRepository.Create
func (mmCreate *mCommentRepositoryMockCreate) Return(c2 model.Comment, err error) *CommentRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &CommentRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &CommentRepositoryMockCreateResults{c2, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the CommentRepository.Create method
func (mmCreate *mCommentRepositoryMockCreate) Set(f func(ctx context.Context, comment model.Comment) (c2 model.Comment, err error)) *CommentRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the CommentRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the CommentRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the CommentRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mCommentRepositoryMockCreate) When(ctx context.Context, comment model.Comment) *CommentRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("CommentRepositoryMock.Create mock is already set by Set")
	}

	expectation := &CommentRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &CommentRepositoryMockCreateParams{ctx, comment},
		expectationOrigins: CommentRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up CommentRepository.Create return parameters for the expectation previously defined by the When method
func (e *CommentRepositoryMockCreateExpectation) Then(c2 model.Comment, err error) *CommentRepositoryMock {
	e.results = &CommentRepositoryMockCreateResults{c2, err}
	return e.mock
}

// Times sets number of times CommentRepository.Create should be invoked
func (mmCreate *mCommentRepositoryMockCreate) Times(n uint64) *mCommentRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of CommentRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mCommentRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_usecase.CommentRepository
func (mmCreate *CommentRepositoryMock) Create(ctx context.Context, comment model.Comment) (c2 model.Comment, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, comment)
	}

	mm_params := CommentRepositoryMockCreateParams{ctx, comment}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := CommentRepositoryMockCreateParams{ctx, comment}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("CommentRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.comment != nil && !minimock.Equal(*mm_want_ptrs.comment, mm_got.comment) {
				mmCreate.t.Errorf("CommentRepositoryMock.Create got unexpected parameter comment, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originComment, *mm_want_ptrs.comment, mm_got.comment, minimock.Diff(*mm_want_ptrs.comment, mm_got.comment))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("CommentRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the CommentRepositoryMock.Create")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, comment)
	}
	mmCreate.t.Fatalf("Unexpected call to CommentRepositoryMock.Create. %v %v", ctx, comment)
	return
}

// CreateAfterCounter returns a count of finished CommentRepositoryMock.Create invocations
func (mmCreate *CommentRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of CommentRepositoryMock.Create invocations
func (mmCreate *CommentRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to CommentRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mCommentRepositoryMockCreate) Calls() []*CommentRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*CommentRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *CommentRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *CommentRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to CommentRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mCommentRepositoryMockGetByID struct {
	optional           bool
	mock               *CommentRepositoryMock
	defaultExpectation *CommentRepositoryMockGetByIDExpectation
	expectations       []*CommentRepositoryMockGetByIDExpectation

	callArgs []*CommentRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentRepositoryMockGetByIDExpectation specifies expectation struct of the CommentRepository.GetByID
type CommentRepositoryMockGetByIDExpectation struct {
	mock               *CommentRepositoryMock
	params             *CommentRepositoryMockGetByIDParams
	paramPtrs          *CommentRepositoryMockGetByIDParamPtrs
	expectationOrigins CommentRepositoryMockGetByIDExpectationOrigins
	results            *CommentRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// CommentRepositoryMockGetByIDParams contains parameters of the CommentRepository.GetByID
type CommentRepositoryMockGetByIDParams struct {
	ctx context.Context
	id  int64
}

// CommentRepositoryMockGetByIDParamPtrs contains pointers to parameters of the CommentRepository.GetByID
type CommentRepositoryMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// CommentRepositoryMockGetByIDResults contains results of the CommentRepository.GetByID
type CommentRepositoryMockGetByIDResults struct {
	c2  model.Comment
	err error
}

// CommentRepositoryMockGetByIDOrigins contains origins of expectations of the CommentRepository.GetByID
type CommentRepositoryMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mCommentRepositoryMockGetByID) Optional() *mCommentRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for CommentRepository.GetByID
func (mmGetByID *mCommentRepositoryMockGetByID) Expect(ctx context.Context, id int64) *mCommentRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &CommentRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &CommentRepositoryMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for CommentRepository.GetByID
func (mmGetByID *mCommentRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mCommentRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &CommentRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &CommentRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for CommentRepository.GetByID
func (mmGetByID *mCommentRepositoryMockGetByID) ExpectIdParam2(id int64) *mCommentRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &CommentRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &CommentRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the CommentRepository.GetByID
func (mmGetByID *mCommentRepositoryMockGetByID) Inspect(f func(ctx context.Context, id int64)) *mCommentRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for CommentRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by CommentRepository.GetByID
func (mmGetByID *mCommentRepositoryMockGetByID) Return(c2 model.Comment, err error) *CommentRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &CommentRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &CommentRepositoryMockGetByIDResults{c2, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the CommentRepository.GetByID method
func (mmGetByID *mCommentRepositoryMockGetByID) Set(f func(ctx context.Context, id int64) (c2 model.Comment, err error)) *CommentRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the CommentRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the CommentRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the CommentRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mCommentRepositoryMockGetByID) When(ctx context.Context, id int64) *CommentRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("CommentRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &CommentRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &CommentRepositoryMockGetByIDParams{ctx, id},
		expectationOrigins: CommentRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up CommentRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *CommentRepositoryMockGetByIDExpectation) Then(c2 model.Comment, err error) *CommentRepositoryMock {
	e.results = &CommentRepositoryMockGetByIDResults{c2, err}
	return e.mock
}

// Times sets number of times CommentRepository.GetByID should be invoked
func (mmGetByID *mCommentRepositoryMockGetByID) Times(n uint64) *mCommentRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of CommentRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mCommentRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_usecase.CommentRepository
func (mmGetByID *CommentRepositoryMock) GetByID(ctx context.Context, id int64) (c2 model.Comment, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := CommentRepositoryMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := CommentRepositoryMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("CommentRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("CommentRepositoryMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("CommentRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the CommentRepositoryMock.GetByID")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to CommentRepositoryMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished CommentRepositoryMock.GetByID invocations
func (mmGetByID *CommentRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of CommentRepositoryMock.GetByID invocations
func (mmGetByID *CommentRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to CommentRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mCommentRepositoryMockGetByID) Calls() []*CommentRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*CommentRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *CommentRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *CommentRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to CommentRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mCommentRepositoryMockListByPostAndParent struct {
	optional           bool
	mock               *CommentRepositoryMock
	defaultExpectation *CommentRepositoryMockListByPostAndParentExpectation
	expectations       []*CommentRepositoryMockListByPostAndParentExpectation

	callArgs []*CommentRepositoryMockListByPostAndParentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentRepositoryMockListByPostAndParentExpectation specifies expectation struct of the CommentRepository.ListByPostAndParent
type CommentRepositoryMockListByPostAndParentExpectation struct {
	mock               *CommentRepositoryMock
	params             *CommentRepositoryMockListByPostAndParentParams
	paramPtrs          *CommentRepositoryMockListByPostAndParentParamPtrs
	expectationOrigins CommentRepositoryMockListByPostAndParentExpectationOrigins
	results            *CommentRepositoryMockListByPostAndParentResults
	returnOrigin       string
	Counter            uint64
}

// CommentRepositoryMockListByPostAndParentParams contains parameters of the CommentRepository.ListByPostAndParent
type CommentRepositoryMockListByPostAndParentParams struct {
	ctx    context.Context
	filter model.CommentListFilter
}

// CommentRepositoryMockListByPostAndParentParamPtrs contains pointers to parameters of the CommentRepository.ListByPostAndParent
type CommentRepositoryMockListByPostAndParentParamPtrs struct {
	ctx    *context.Context
	filter *model.CommentListFilter
}

// CommentRepositoryMockListByPostAndParentResults contains results of the CommentRepository.ListByPostAndParent
type CommentRepositoryMockListByPostAndParentResults struct {
	ca1 []model.Comment
	b1  bool
	err error
}

// CommentRepositoryMockListByPostAndParentOrigins contains origins of expectations of the CommentRepository.ListByPostAndParent
type CommentRepositoryMockListByPostAndParentExpectationOrigins struct {
	origin       string
	originCtx    string
	originFilter string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Optional() *mCommentRepositoryMockListByPostAndParent {
	mmListByPostAndParent.optional = true
	return mmListByPostAndParent
}

// Expect sets up expected params for CommentRepository.ListByPostAndParent
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Expect(ctx context.Context, filter model.CommentListFilter) *mCommentRepositoryMockListByPostAndParent {
	if mmListByPostAndParent.mock.funcListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Set")
	}

	if mmListByPostAndParent.defaultExpectation == nil {
		mmListByPostAndParent.defaultExpectation = &CommentRepositoryMockListByPostAndParentExpectation{}
	}

	if mmListByPostAndParent.defaultExpectation.paramPtrs != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by ExpectParams functions")
	}

	mmListByPostAndParent.defaultExpectation.params = &CommentRepositoryMockListByPostAndParentParams{ctx, filter}
	mmListByPostAndParent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListByPostAndParent.expectations {
		if minimock.Equal(e.params, mmListByPostAndParent.defaultExpectation.params) {
			mmListByPostAndParent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListByPostAndParent.defaultExpectation.params)
		}
	}

	return mmListByPostAndParent
}

// ExpectCtxParam1 sets up expected param ctx for CommentRepository.ListByPostAndParent
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) ExpectCtxParam1(ctx context.Context) *mCommentRepositoryMockListByPostAndParent {
	if mmListByPostAndParent.mock.funcListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Set")
	}

	if mmListByPostAndParent.defaultExpectation == nil {
		mmListByPostAndParent.defaultExpectation = &CommentRepositoryMockListByPostAndParentExpectation{}
	}

	if mmListByPostAndParent.defaultExpectation.params != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Expect")
	}

	if mmListByPostAndParent.defaultExpectation.paramPtrs == nil {
		mmListByPostAndParent.defaultExpectation.paramPtrs = &CommentRepositoryMockListByPostAndParentParamPtrs{}
	}
	mmListByPostAndParent.defaultExpectation.paramPtrs.ctx = &ctx
	mmListByPostAndParent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListByPostAndParent
}

// ExpectFilterParam2 sets up expected param filter for CommentRepository.ListByPostAndParent
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) ExpectFilterParam2(filter model.CommentListFilter) *mCommentRepositoryMockListByPostAndParent {
	if mmListByPostAndParent.mock.funcListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Set")
	}

	if mmListByPostAndParent.defaultExpectation == nil {
		mmListByPostAndParent.defaultExpectation = &CommentRepositoryMockListByPostAndParentExpectation{}
	}

	if mmListByPostAndParent.defaultExpectation.params != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Expect")
	}

	if mmListByPostAndParent.defaultExpectation.paramPtrs == nil {
		mmListByPostAndParent.defaultExpectation.paramPtrs = &CommentRepositoryMockListByPostAndParentParamPtrs{}
	}
	mmListByPostAndParent.defaultExpectation.paramPtrs.filter = &filter
	mmListByPostAndParent.defaultExpectation.expectationOrigins.originFilter = minimock.CallerInfo(1)

	return mmListByPostAndParent
}

// Inspect accepts an inspector function that has same arguments as the CommentRepository.ListByPostAndParent
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Inspect(f func(ctx context.Context, filter model.CommentListFilter)) *mCommentRepositoryMockListByPostAndParent {
	if mmListByPostAndParent.mock.inspectFuncListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("Inspect function is already set for CommentRepositoryMock.ListByPostAndParent")
	}

	mmListByPostAndParent.mock.inspectFuncListByPostAndParent = f

	return mmListByPostAndParent
}

// Return sets up results that will be returned by CommentRepository.ListByPostAndParent
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Return(ca1 []model.Comment, b1 bool, err error) *CommentRepositoryMock {
	if mmListByPostAndParent.mock.funcListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Set")
	}

	if mmListByPostAndParent.defaultExpectation == nil {
		mmListByPostAndParent.defaultExpectation = &CommentRepositoryMockListByPostAndParentExpectation{mock: mmListByPostAndParent.mock}
	}
	mmListByPostAndParent.defaultExpectation.results = &CommentRepositoryMockListByPostAndParentResults{ca1, b1, err}
	mmListByPostAndParent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListByPostAndParent.mock
}

// Set uses given function f to mock the CommentRepository.ListByPostAndParent method
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Set(f func(ctx context.Context, filter model.CommentListFilter) (ca1 []model.Comment, b1 bool, err error)) *CommentRepositoryMock {
	if mmListByPostAndParent.defaultExpectation != nil {
		mmListByPostAndParent.mock.t.Fatalf("Default expectation is already set for the CommentRepository.ListByPostAndParent method")
	}

	if len(mmListByPostAndParent.expectations) > 0 {
		mmListByPostAndParent.mock.t.Fatalf("Some expectations are already set for the CommentRepository.ListByPostAndParent method")
	}

	mmListByPostAndParent.mock.funcListByPostAndParent = f
	mmListByPostAndParent.mock.funcListByPostAndParentOrigin = minimock.CallerInfo(1)
	return mmListByPostAndParent.mock
}

// When sets expectation for the CommentRepository.ListByPostAndParent which will trigger the result defined by the following
// Then helper
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) When(ctx context.Context, filter model.CommentListFilter) *CommentRepositoryMockListByPostAndParentExpectation {
	if mmListByPostAndParent.mock.funcListByPostAndParent != nil {
		mmListByPostAndParent.mock.t.Fatalf("CommentRepositoryMock.ListByPostAndParent mock is already set by Set")
	}

	expectation := &CommentRepositoryMockListByPostAndParentExpectation{
		mock:               mmListByPostAndParent.mock,
		params:             &CommentRepositoryMockListByPostAndParentParams{ctx, filter},
		expectationOrigins: CommentRepositoryMockListByPostAndParentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListByPostAndParent.expectations = append(mmListByPostAndParent.expectations, expectation)
	return expectation
}

// Then sets up CommentRepository.ListByPostAndParent return parameters for the expectation previously defined by the When method
func (e *CommentRepositoryMockListByPostAndParentExpectation) Then(ca1 []model.Comment, b1 bool, err error) *CommentRepositoryMock {
	e.results = &CommentRepositoryMockListByPostAndParentResults{ca1, b1, err}
	return e.mock
}

// Times sets number of times CommentRepository.ListByPostAndParent should be invoked
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Times(n uint64) *mCommentRepositoryMockListByPostAndParent {
	if n == 0 {
		mmListByPostAndParent.mock.t.Fatalf("Times of CommentRepositoryMock.ListByPostAndParent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListByPostAndParent.expectedInvocations, n)
	mmListByPostAndParent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListByPostAndParent
}

func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) invocationsDone() bool {
	if len(mmListByPostAndParent.expectations) == 0 && mmListByPostAndParent.defaultExpectation == nil && mmListByPostAndParent.mock.funcListByPostAndParent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListByPostAndParent.mock.afterListByPostAndParentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListByPostAndParent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListByPostAndParent implements mm_usecase.CommentRepository
func (mmListByPostAndParent *CommentRepositoryMock) ListByPostAndParent(ctx context.Context, filter model.CommentListFilter) (ca1 []model.Comment, b1 bool, err error) {
	mm_atomic.AddUint64(&mmListByPostAndParent.beforeListByPostAndParentCounter, 1)
	defer mm_atomic.AddUint64(&mmListByPostAndParent.afterListByPostAndParentCounter, 1)

	mmListByPostAndParent.t.Helper()

	if mmListByPostAndParent.inspectFuncListByPostAndParent != nil {
		mmListByPostAndParent.inspectFuncListByPostAndParent(ctx, filter)
	}

	mm_params := CommentRepositoryMockListByPostAndParentParams{ctx, filter}

	// Record call args
	mmListByPostAndParent.ListByPostAndParentMock.mutex.Lock()
	mmListByPostAndParent.ListByPostAndParentMock.callArgs = append(mmListByPostAndParent.ListByPostAndParentMock.callArgs, &mm_params)
	mmListByPostAndParent.ListByPostAndParentMock.mutex.Unlock()

	for _, e := range mmListByPostAndParent.ListByPostAndParentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ca1, e.results.b1, e.results.err
		}
	}

	if mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.Counter, 1)
		mm_want := mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.params
		mm_want_ptrs := mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.paramPtrs

		mm_got := CommentRepositoryMockListByPostAndParentParams{ctx, filter}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListByPostAndParent.t.Errorf("CommentRepositoryMock.ListByPostAndParent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.filter != nil && !minimock.Equal(*mm_want_ptrs.filter, mm_got.filter) {
				mmListByPostAndParent.t.Errorf("CommentRepositoryMock.ListByPostAndParent got unexpected parameter filter, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.expectationOrigins.originFilter, *mm_want_ptrs.filter, mm_got.filter, minimock.Diff(*mm_want_ptrs.filter, mm_got.filter))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListByPostAndParent.t.Errorf("CommentRepositoryMock.ListByPostAndParent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListByPostAndParent.ListByPostAndParentMock.defaultExpectation.results
		if mm_results == nil {
			mmListByPostAndParent.t.Fatal("No results are set for the CommentRepositoryMock.ListByPostAndParent")
		}
		return (*mm_results).ca1, (*mm_results).b1, (*mm_results).err
	}
	if mmListByPostAndParent.funcListByPostAndParent != nil {
		return mmListByPostAndParent.funcListByPostAndParent(ctx, filter)
	}
	mmListByPostAndParent.t.Fatalf("Unexpected call to CommentRepositoryMock.ListByPostAndParent. %v %v", ctx, filter)
	return
}

// ListByPostAndParentAfterCounter returns a count of finished CommentRepositoryMock.ListByPostAndParent invocations
func (mmListByPostAndParent *CommentRepositoryMock) ListByPostAndParentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByPostAndParent.afterListByPostAndParentCounter)
}

// ListByPostAndParentBeforeCounter returns a count of CommentRepositoryMock.ListByPostAndParent invocations
func (mmListByPostAndParent *CommentRepositoryMock) ListByPostAndParentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByPostAndParent.beforeListByPostAndParentCounter)
}

// Calls returns a list of arguments used in each call to CommentRepositoryMock.ListByPostAndParent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListByPostAndParent *mCommentRepositoryMockListByPostAndParent) Calls() []*CommentRepositoryMockListByPostAndParentParams {
	mmListByPostAndParent.mutex.RLock()

	argCopy := make([]*CommentRepositoryMockListByPostAndParentParams, len(mmListByPostAndParent.callArgs))
	copy(argCopy, mmListByPostAndParent.callArgs)

	mmListByPostAndParent.mutex.RUnlock()

	return argCopy
}

// MinimockListByPostAndParentDone returns true if the count of the ListByPostAndParent invocations corresponds
// the number of defined expectations
func (m *CommentRepositoryMock) MinimockListByPostAndParentDone() bool {
	if m.ListByPostAndParentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListByPostAndParentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListByPostAndParentMock.invocationsDone()
}

// MinimockListByPostAndParentInspect logs each unmet expectation
func (m *CommentRepositoryMock) MinimockListByPostAndParentInspect() {
	for _, e := range m.ListByPostAndParentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentRepositoryMock.ListByPostAndParent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListByPostAndParentCounter := mm_atomic.LoadUint64(&m.afterListByPostAndParentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListByPostAndParentMock.defaultExpectation != nil && afterListByPostAndParentCounter < 1 {
		if m.ListByPostAndParentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentRepositoryMock.ListByPostAndParent at\n%s", m.ListByPostAndParentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentRepositoryMock.ListByPostAndParent at\n%s with params: %#v", m.ListByPostAndParentMock.defaultExpectation.expectationOrigins.origin, *m.ListByPostAndParentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListByPostAndParent != nil && afterListByPostAndParentCounter < 1 {
		m.t.Errorf("Expected call to CommentRepositoryMock.ListByPostAndParent at\n%s", m.funcListByPostAndParentOrigin)
	}

	if !m.ListByPostAndParentMock.invocationsDone() && afterListByPostAndParentCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentRepositoryMock.ListByPostAndParent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListByPostAndParentMock.expectedInvocations), m.ListByPostAndParentMock.expectedInvocationsOrigin, afterListByPostAndParentCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CommentRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByIDInspect()

			m.MinimockListByPostAndParentInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CommentRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CommentRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockListByPostAndParentDone()
}
