// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-grapql-service/internal/usecase.CommentProducer -o comment_producer_mock.go -n CommentProducerMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-grapql-service/internal/model"
)

// CommentProducerMock implements mm_usecase.CommentProducer
type CommentProducerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPublishComment          func(ctx context.Context, comment model.Comment)
	funcPublishCommentOrigin    string
	inspectFuncPublishComment   func(ctx context.Context, comment model.Comment)
	afterPublishCommentCounter  uint64
	beforePublishCommentCounter uint64
	PublishCommentMock          mCommentProducerMockPublishComment
}

// NewCommentProducerMock returns a mock for mm_usecase.CommentProducer
func NewCommentProducerMock(t minimock.Tester) *CommentProducerMock {
	m := &CommentProducerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PublishCommentMock = mCommentProducerMockPublishComment{mock: m}
	m.PublishCommentMock.callArgs = []*CommentProducerMockPublishCommentParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCommentProducerMockPublishComment struct {
	optional           bool
	mock               *CommentProducerMock
	defaultExpectation *CommentProducerMockPublishCommentExpectation
	expectations       []*CommentProducerMockPublishCommentExpectation

	callArgs []*CommentProducerMockPublishCommentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentProducerMockPublishCommentExpectation specifies expectation struct of the CommentProducer.PublishComment
type CommentProducerMockPublishCommentExpectation struct {
	mock               *CommentProducerMock
	params             *CommentProducerMockPublishCommentParams
	paramPtrs          *CommentProducerMockPublishCommentParamPtrs
	expectationOrigins CommentProducerMockPublishCommentExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// CommentProducerMockPublishCommentParams contains parameters of the CommentProducer.PublishComment
type CommentProducerMockPublishCommentParams struct {
	ctx     context.Context
	comment model.Comment
}

// CommentProducerMockPublishCommentParamPtrs contains pointers to parameters of the CommentProducer.PublishComment
type CommentProducerMockPublishCommentParamPtrs struct {
	ctx     *context.Context
	comment *model.Comment
}

// CommentProducerMockPublishCommentOrigins contains origins of expectations of the CommentProducer.PublishComment
type CommentProducerMockPublishCommentExpectationOrigins struct {
	origin        string
	originCtx     string
	originComment string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPublishComment *mCommentProducerMockPublishComment) Optional() *mCommentProducerMockPublishComment {
	mmPublishComment.optional = true
	return mmPublishComment
}

// Expect sets up expected params for CommentProducer.PublishComment
func (mmPublishComment *mCommentProducerMockPublishComment) Expect(ctx context.Context, comment model.Comment) *mCommentProducerMockPublishComment {
	if mmPublishComment.mock.funcPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Set")
	}

	if mmPublishComment.defaultExpectation == nil {
		mmPublishComment.defaultExpectation = &CommentProducerMockPublishCommentExpectation{}
	}

	if mmPublishComment.defaultExpectation.paramPtrs != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by ExpectParams functions")
	}

	mmPublishComment.defaultExpectation.params = &CommentProducerMockPublishCommentParams{ctx, comment}
	mmPublishComment.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPublishComment.expectations {
		if minimock.Equal(e.params, mmPublishComment.defaultExpectation.params) {
			mmPublishComment.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPublishComment.defaultExpectation.params)
		}
	}

	return mmPublishComment
}

// ExpectCtxParam1 sets up expected param ctx for CommentProducer.PublishComment
func (mmPublishComment *mCommentProducerMockPublishComment) ExpectCtxParam1(ctx context.Context) *mCommentProducerMockPublishComment {
	if mmPublishComment.mock.funcPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Set")
	}

	if mmPublishComment.defaultExpectation == nil {
		mmPublishComment.defaultExpectation = &CommentProducerMockPublishCommentExpectation{}
	}

	if mmPublishComment.defaultExpectation.params != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Expect")
	}

	if mmPublishComment.defaultExpectation.paramPtrs == nil {
		mmPublishComment.defaultExpectation.paramPtrs = &CommentProducerMockPublishCommentParamPtrs{}
	}
	mmPublishComment.defaultExpectation.paramPtrs.ctx = &ctx
	mmPublishComment.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPublishComment
}

// ExpectCommentParam2 sets up expected param comment for CommentProducer.PublishComment
func (mmPublishComment *mCommentProducerMockPublishComment) ExpectCommentParam2(comment model.Comment) *mCommentProducerMockPublishComment {
	if mmPublishComment.mock.funcPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Set")
	}

	if mmPublishComment.defaultExpectation == nil {
		mmPublishComment.defaultExpectation = &CommentProducerMockPublishCommentExpectation{}
	}

	if mmPublishComment.defaultExpectation.params != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Expect")
	}

	if mmPublishComment.defaultExpectation.paramPtrs == nil {
		mmPublishComment.defaultExpectation.paramPtrs = &CommentProducerMockPublishCommentParamPtrs{}
	}
	mmPublishComment.defaultExpectation.paramPtrs.comment = &comment
	mmPublishComment.defaultExpectation.expectationOrigins.originComment = minimock.CallerInfo(1)

	return mmPublishComment
}

// Inspect accepts an inspector function that has same arguments as the CommentProducer.PublishComment
func (mmPublishComment *mCommentProducerMockPublishComment) Inspect(f func(ctx context.Context, comment model.Comment)) *mCommentProducerMockPublishComment {
	if mmPublishComment.mock.inspectFuncPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("Inspect function is already set for CommentProducerMock.PublishComment")
	}

	mmPublishComment.mock.inspectFuncPublishComment = f

	return mmPublishComment
}

// Return sets up results that will be returned by CommentProducer.PublishComment
func (mmPublishComment *mCommentProducerMockPublishComment) Return() *CommentProducerMock {
	if mmPublishComment.mock.funcPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Set")
	}

	if mmPublishComment.defaultExpectation == nil {
		mmPublishComment.defaultExpectation = &CommentProducerMockPublishCommentExpectation{mock: mmPublishComment.mock}
	}

	mmPublishComment.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPublishComment.mock
}

// Set uses given function f to mock the CommentProducer.PublishComment method
func (mmPublishComment *mCommentProducerMockPublishComment) Set(f func(ctx context.Context, comment model.Comment)) *CommentProducerMock {
	if mmPublishComment.defaultExpectation != nil {
		mmPublishComment.mock.t.Fatalf("Default expectation is already set for the CommentProducer.PublishComment method")
	}

	if len(mmPublishComment.expectations) > 0 {
		mmPublishComment.mock.t.Fatalf("Some expectations are already set for the CommentProducer.PublishComment method")
	}

	mmPublishComment.mock.funcPublishComment = f
	mmPublishComment.mock.funcPublishCommentOrigin = minimock.CallerInfo(1)
	return mmPublishComment.mock
}

// When sets expectation for the CommentProducer.PublishComment which will trigger the result defined by the following
// Then helper
func (mmPublishComment *mCommentProducerMockPublishComment) When(ctx context.Context, comment model.Comment) *CommentProducerMockPublishCommentExpectation {
	if mmPublishComment.mock.funcPublishComment != nil {
		mmPublishComment.mock.t.Fatalf("CommentProducerMock.PublishComment mock is already set by Set")
	}

	expectation := &CommentProducerMockPublishCommentExpectation{
		mock:               mmPublishComment.mock,
		params:             &CommentProducerMockPublishCommentParams{ctx, comment},
		expectationOrigins: CommentProducerMockPublishCommentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPublishComment.expectations = append(mmPublishComment.expectations, expectation)
	return expectation
}

// Then sets up CommentProducer.PublishComment return parameters for the expectation previously defined by the When method

func (e *CommentProducerMockPublishCommentExpectation) Then() *CommentProducerMock {
	return e.mock
}

// Times sets number of times CommentProducer.PublishComment should be invoked
func (mmPublishComment *mCommentProducerMockPublishComment) Times(n uint64) *mCommentProducerMockPublishComment {
	if n == 0 {
		mmPublishComment.mock.t.Fatalf("Times of CommentProducerMock.PublishComment mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPublishComment.expectedInvocations, n)
	mmPublishComment.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPublishComment
}

func (mmPublishComment *mCommentProducerMockPublishComment) invocationsDone() bool {
	if len(mmPublishComment.expectations) == 0 && mmPublishComment.defaultExpectation == nil && mmPublishComment.mock.funcPublishComment == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPublishComment.mock.afterPublishCommentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPublishComment.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PublishComment implements mm_usecase.CommentProducer
func (mmPublishComment *CommentProducerMock) PublishComment(ctx context.Context, comment model.Comment) {
	mm_atomic.AddUint64(&mmPublishComment.beforePublishCommentCounter, 1)
	defer mm_atomic.AddUint64(&mmPublishComment.afterPublishCommentCounter, 1)

	mmPublishComment.t.Helper()

	if mmPublishComment.inspectFuncPublishComment != nil {
		mmPublishComment.inspectFuncPublishComment(ctx, comment)
	}

	mm_params := CommentProducerMockPublishCommentParams{ctx, comment}

	// Record call args
	mmPublishComment.PublishCommentMock.mutex.Lock()
	mmPublishComment.PublishCommentMock.callArgs = append(mmPublishComment.PublishCommentMock.callArgs, &mm_params)
	mmPublishComment.PublishCommentMock.mutex.Unlock()

	for _, e := range mmPublishComment.PublishCommentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmPublishComment.PublishCommentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPublishComment.PublishCommentMock.defaultExpectation.Counter, 1)
		mm_want := mmPublishComment.PublishCommentMock.defaultExpectation.params
		mm_want_ptrs := mmPublishComment.PublishCommentMock.defaultExpectation.paramPtrs

		mm_got := CommentProducerMockPublishCommentParams{ctx, comment}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPublishComment.t.Errorf("CommentProducerMock.PublishComment got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishComment.PublishCommentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.comment != nil && !minimock.Equal(*mm_want_ptrs.comment, mm_got.comment) {
				mmPublishComment.t.Errorf("CommentProducerMock.PublishComment got unexpected parameter comment, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishComment.PublishCommentMock.defaultExpectation.expectationOrigins.originComment, *mm_want_ptrs.comment, mm_got.comment, minimock.Diff(*mm_want_ptrs.comment, mm_got.comment))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPublishComment.t.Errorf("CommentProducerMock.PublishComment got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPublishComment.PublishCommentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmPublishComment.funcPublishComment != nil {
		mmPublishComment.funcPublishComment(ctx, comment)
		return
	}
	mmPublishComment.t.Fatalf("Unexpected call to CommentProducerMock.PublishComment. %v %v", ctx, comment)

}

// PublishCommentAfterCounter returns a count of finished CommentProducerMock.PublishComment invocations
func (mmPublishComment *CommentProducerMock) PublishCommentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishComment.afterPublishCommentCounter)
}

// PublishCommentBeforeCounter returns a count of CommentProducerMock.PublishComment invocations
func (mmPublishComment *CommentProducerMock) PublishCommentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishComment.beforePublishCommentCounter)
}

// Calls returns a list of arguments used in each call to CommentProducerMock.PublishComment.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPublishComment *mCommentProducerMockPublishComment) Calls() []*CommentProducerMockPublishCommentParams {
	mmPublishComment.mutex.RLock()

	argCopy := make([]*CommentProducerMockPublishCommentParams, len(mmPublishComment.callArgs))
	copy(argCopy, mmPublishComment.callArgs)

	mmPublishComment.mutex.RUnlock()

	return argCopy
}

// MinimockPublishCommentDone returns true if the count of the PublishComment invocations corresponds
// the number of defined expectations
func (m *CommentProducerMock) MinimockPublishCommentDone() bool {
	if m.PublishCommentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PublishCommentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PublishCommentMock.invocationsDone()
}

// MinimockPublishCommentInspect logs each unmet expectation
func (m *CommentProducerMock) MinimockPublishCommentInspect() {
	for _, e := range m.PublishCommentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentProducerMock.PublishComment at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPublishCommentCounter := mm_atomic.LoadUint64(&m.afterPublishCommentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PublishCommentMock.defaultExpectation != nil && afterPublishCommentCounter < 1 {
		if m.PublishCommentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentProducerMock.PublishComment at\n%s", m.PublishCommentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentProducerMock.PublishComment at\n%s with params: %#v", m.PublishCommentMock.defaultExpectation.expectationOrigins.origin, *m.PublishCommentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPublishComment != nil && afterPublishCommentCounter < 1 {
		m.t.Errorf("Expected call to CommentProducerMock.PublishComment at\n%s", m.funcPublishCommentOrigin)
	}

	if !m.PublishCommentMock.invocationsDone() && afterPublishCommentCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentProducerMock.PublishComment at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PublishCommentMock.expectedInvocations), m.PublishCommentMock.expectedInvocationsOrigin, afterPublishCommentCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CommentProducerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPublishCommentInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CommentProducerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CommentProducerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPublishCommentDone()
}
