// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-graphql-service/internal/usecase.PostRepository -o post_repository_mock.go -n PostRepositoryMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-graphql-service/internal/model"
)

// PostRepositoryMock implements mm_usecase.PostRepository
type PostRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, post model.Post) (p1 model.Post, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, post model.Post)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mPostRepositoryMockCreate

	funcGetByID          func(ctx context.Context, id int64) (p1 model.Post, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id int64)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mPostRepositoryMockGetByID

	funcList          func(ctx context.Context) (pa1 []model.Post, err error)
	funcListOrigin    string
	inspectFuncList   func(ctx context.Context)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mPostRepositoryMockList

	funcUpdateCommentsAvailability          func(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error)
	funcUpdateCommentsAvailabilityOrigin    string
	inspectFuncUpdateCommentsAvailability   func(ctx context.Context, postID int64, enabled bool)
	afterUpdateCommentsAvailabilityCounter  uint64
	beforeUpdateCommentsAvailabilityCounter uint64
	UpdateCommentsAvailabilityMock          mPostRepositoryMockUpdateCommentsAvailability
}

// NewPostRepositoryMock returns a mock for mm_usecase.PostRepository
func NewPostRepositoryMock(t minimock.Tester) *PostRepositoryMock {
	m := &PostRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mPostRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*PostRepositoryMockCreateParams{}

	m.GetByIDMock = mPostRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*PostRepositoryMockGetByIDParams{}

	m.ListMock = mPostRepositoryMockList{mock: m}
	m.ListMock.callArgs = []*PostRepositoryMockListParams{}

	m.UpdateCommentsAvailabilityMock = mPostRepositoryMockUpdateCommentsAvailability{mock: m}
	m.UpdateCommentsAvailabilityMock.callArgs = []*PostRepositoryMockUpdateCommentsAvailabilityParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPostRepositoryMockCreate struct {
	optional           bool
	mock               *PostRepositoryMock
	defaultExpectation *PostRepositoryMockCreateExpectation
	expectations       []*PostRepositoryMockCreateExpectation

	callArgs []*PostRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostRepositoryMockCreateExpectation specifies expectation struct of the PostRepository.Create
type PostRepositoryMockCreateExpectation struct {
	mock               *PostRepositoryMock
	params             *PostRepositoryMockCreateParams
	paramPtrs          *PostRepositoryMockCreateParamPtrs
	expectationOrigins PostRepositoryMockCreateExpectationOrigins
	results            *PostRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// PostRepositoryMockCreateParams contains parameters of the PostRepository.Create
type PostRepositoryMockCreateParams struct {
	ctx  context.Context
	post model.Post
}

// PostRepositoryMockCreateParamPtrs contains pointers to parameters of the PostRepository.Create
type PostRepositoryMockCreateParamPtrs struct {
	ctx  *context.Context
	post *model.Post
}

// PostRepositoryMockCreateResults contains results of the PostRepository.Create
type PostRepositoryMockCreateResults struct {
	p1  model.Post
	err error
}

// PostRepositoryMockCreateOrigins contains origins of expectations of the PostRepository.Create
type PostRepositoryMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originPost string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mPostRepositoryMockCreate) Optional() *mPostRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for PostRepository.Create
func (mmCreate *mPostRepositoryMockCreate) Expect(ctx context.Context, post model.Post) *mPostRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &PostRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &PostRepositoryMockCreateParams{ctx, post}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for PostRepository.Create
func (mmCreate *mPostRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mPostRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &PostRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &PostRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectPostParam2 sets up expected param post for PostRepository.Create
func (mmCreate *mPostRepositoryMockCreate) ExpectPostParam2(post model.Post) *mPostRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &PostRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &PostRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.post = &post
	mmCreate.defaultExpectation.expectationOrigins.originPost = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the PostRepository.Create
func (mmCreate *mPostRepositoryMockCreate) Inspect(f func(ctx context.Context, post model.Post)) *mPostRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for PostRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by PostRepository.Create
func (mmCreate *mPostRepositoryMockCreate) Return(p1 model.Post, err error) *PostRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &PostRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &PostRepositoryMockCreateResults{p1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the PostRepository.Create method
func (mmCreate *mPostRepositoryMockCreate) Set(f func(ctx context.Context, post model.Post) (p1 model.Post, err error)) *PostRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the PostRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the PostRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the PostRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mPostRepositoryMockCreate) When(ctx context.Context, post model.Post) *PostRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("PostRepositoryMock.Create mock is already set by Set")
	}

	expectation := &PostRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &PostRepositoryMockCreateParams{ctx, post},
		expectationOrigins: PostRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up PostRepository.Create return parameters for the expectation previously defined by the When method
func (e *PostRepositoryMockCreateExpectation) Then(p1 model.Post, err error) *PostRepositoryMock {
	e.results = &PostRepositoryMockCreateResults{p1, err}
	return e.mock
}

// Times sets number of times PostRepository.Create should be invoked
func (mmCreate *mPostRepositoryMockCreate) Times(n uint64) *mPostRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of PostRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mPostRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_usecase.PostRepository
func (mmCreate *PostRepositoryMock) Create(ctx context.Context, post model.Post) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, post)
	}

	mm_params := PostRepositoryMockCreateParams{ctx, post}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := PostRepositoryMockCreateParams{ctx, post}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("PostRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.post != nil && !minimock.Equal(*mm_want_ptrs.post, mm_got.post) {
				mmCreate.t.Errorf("PostRepositoryMock.Create got unexpected parameter post, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originPost, *mm_want_ptrs.post, mm_got.post, minimock.Diff(*mm_want_ptrs.post, mm_got.post))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("PostRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the PostRepositoryMock.Create")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, post)
	}
	mmCreate.t.Fatalf("Unexpected call to PostRepositoryMock.Create. %v %v", ctx, post)
	return
}

// CreateAfterCounter returns a count of finished PostRepositoryMock.Create invocations
func (mmCreate *PostRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of PostRepositoryMock.Create invocations
func (mmCreate *PostRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to PostRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mPostRepositoryMockCreate) Calls() []*PostRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*PostRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *PostRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *PostRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to PostRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to PostRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mPostRepositoryMockGetByID struct {
	optional           bool
	mock               *PostRepositoryMock
	defaultExpectation *PostRepositoryMockGetByIDExpectation
	expectations       []*PostRepositoryMockGetByIDExpectation

	callArgs []*PostRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostRepositoryMockGetByIDExpectation specifies expectation struct of the PostRepository.GetByID
type PostRepositoryMockGetByIDExpectation struct {
	mock               *PostRepositoryMock
	params             *PostRepositoryMockGetByIDParams
	paramPtrs          *PostRepositoryMockGetByIDParamPtrs
	expectationOrigins PostRepositoryMockGetByIDExpectationOrigins
	results            *PostRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// PostRepositoryMockGetByIDParams contains parameters of the PostRepository.GetByID
type PostRepositoryMockGetByIDParams struct {
	ctx context.Context
	id  int64
}

// PostRepositoryMockGetByIDParamPtrs contains pointers to parameters of the PostRepository.GetByID
type PostRepositoryMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// PostRepositoryMockGetByIDResults contains results of the PostRepository.GetByID
type PostRepositoryMockGetByIDResults struct {
	p1  model.Post
	err error
}

// PostRepositoryMockGetByIDOrigins contains origins of expectations of the PostRepository.GetByID
type PostRepositoryMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mPostRepositoryMockGetByID) Optional() *mPostRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for PostRepository.GetByID
func (mmGetByID *mPostRepositoryMockGetByID) Expect(ctx context.Context, id int64) *mPostRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &PostRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &PostRepositoryMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for PostRepository.GetByID
func (mmGetByID *mPostRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mPostRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &PostRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &PostRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for PostRepository.GetByID
func (mmGetByID *mPostRepositoryMockGetByID) ExpectIdParam2(id int64) *mPostRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &PostRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &PostRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the PostRepository.GetByID
func (mmGetByID *mPostRepositoryMockGetByID) Inspect(f func(ctx context.Context, id int64)) *mPostRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for PostRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by PostRepository.GetByID
func (mmGetByID *mPostRepositoryMockGetByID) Return(p1 model.Post, err error) *PostRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &PostRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &PostRepositoryMockGetByIDResults{p1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the PostRepository.GetByID method
func (mmGetByID *mPostRepositoryMockGetByID) Set(f func(ctx context.Context, id int64) (p1 model.Post, err error)) *PostRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the PostRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the PostRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the PostRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mPostRepositoryMockGetByID) When(ctx context.Context, id int64) *PostRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("PostRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &PostRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &PostRepositoryMockGetByIDParams{ctx, id},
		expectationOrigins: PostRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up PostRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *PostRepositoryMockGetByIDExpectation) Then(p1 model.Post, err error) *PostRepositoryMock {
	e.results = &PostRepositoryMockGetByIDResults{p1, err}
	return e.mock
}

// Times sets number of times PostRepository.GetByID should be invoked
func (mmGetByID *mPostRepositoryMockGetByID) Times(n uint64) *mPostRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of PostRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mPostRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_usecase.PostRepository
func (mmGetByID *PostRepositoryMock) GetByID(ctx context.Context, id int64) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := PostRepositoryMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := PostRepositoryMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("PostRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("PostRepositoryMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("PostRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the PostRepositoryMock.GetByID")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to PostRepositoryMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished PostRepositoryMock.GetByID invocations
func (mmGetByID *PostRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of PostRepositoryMock.GetByID invocations
func (mmGetByID *PostRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to PostRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mPostRepositoryMockGetByID) Calls() []*PostRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*PostRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *PostRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *PostRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to PostRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to PostRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mPostRepositoryMockList struct {
	optional           bool
	mock               *PostRepositoryMock
	defaultExpectation *PostRepositoryMockListExpectation
	expectations       []*PostRepositoryMockListExpectation

	callArgs []*PostRepositoryMockListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostRepositoryMockListExpectation specifies expectation struct of the PostRepository.List
type PostRepositoryMockListExpectation struct {
	mock               *PostRepositoryMock
	params             *PostRepositoryMockListParams
	paramPtrs          *PostRepositoryMockListParamPtrs
	expectationOrigins PostRepositoryMockListExpectationOrigins
	results            *PostRepositoryMockListResults
	returnOrigin       string
	Counter            uint64
}

// PostRepositoryMockListParams contains parameters of the PostRepository.List
type PostRepositoryMockListParams struct {
	ctx context.Context
}

// PostRepositoryMockListParamPtrs contains pointers to parameters of the PostRepository.List
type PostRepositoryMockListParamPtrs struct {
	ctx *context.Context
}

// PostRepositoryMockListResults contains results of the PostRepository.List
type PostRepositoryMockListResults struct {
	pa1 []model.Post
	err error
}

// PostRepositoryMockListOrigins contains origins of expectations of the PostRepository.List
type PostRepositoryMockListExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mPostRepositoryMockList) Optional() *mPostRepositoryMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for PostRepository.List
func (mmList *mPostRepositoryMockList) Expect(ctx context.Context) *mPostRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &PostRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &PostRepositoryMockListParams{ctx}
	mmList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for PostRepository.List
func (mmList *mPostRepositoryMockList) ExpectCtxParam1(ctx context.Context) *mPostRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &PostRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &PostRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx
	mmList.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the PostRepository.List
func (mmList *mPostRepositoryMockList) Inspect(f func(ctx context.Context)) *mPostRepositoryMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for PostRepositoryMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by PostRepository.List
func (mmList *mPostRepositoryMockList) Return(pa1 []model.Post, err error) *PostRepositoryMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &PostRepositoryMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &PostRepositoryMockListResults{pa1, err}
	mmList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// Set uses given function f to mock the PostRepository.List method
func (mmList *mPostRepositoryMockList) Set(f func(ctx context.Context) (pa1 []model.Post, err error)) *PostRepositoryMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the PostRepository.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the PostRepository.List method")
	}

	mmList.mock.funcList = f
	mmList.mock.funcListOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// When sets expectation for the PostRepository.List which will trigger the result defined by the following
// Then helper
func (mmList *mPostRepositoryMockList) When(ctx context.Context) *PostRepositoryMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("PostRepositoryMock.List mock is already set by Set")
	}

	expectation := &PostRepositoryMockListExpectation{
		mock:               mmList.mock,
		params:             &PostRepositoryMockListParams{ctx},
		expectationOrigins: PostRepositoryMockListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up PostRepository.List return parameters for the expectation previously defined by the When method
func (e *PostRepositoryMockListExpectation) Then(pa1 []model.Post, err error) *PostRepositoryMock {
	e.results = &PostRepositoryMockListResults{pa1, err}
	return e.mock
}

// Times sets number of times PostRepository.List should be invoked
func (mmList *mPostRepositoryMockList) Times(n uint64) *mPostRepositoryMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of PostRepositoryMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	mmList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmList
}

func (mmList *mPostRepositoryMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements mm_usecase.PostRepository
func (mmList *PostRepositoryMock) List(ctx context.Context) (pa1 []model.Post, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	mmList.t.Helper()

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx)
	}

	mm_params := PostRepositoryMockListParams{ctx}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pa1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := PostRepositoryMockListParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("PostRepositoryMock.List got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("PostRepositoryMock.List got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmList.ListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the PostRepositoryMock.List")
		}
		return (*mm_results).pa1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx)
	}
	mmList.t.Fatalf("Unexpected call to PostRepositoryMock.List. %v", ctx)
	return
}

// ListAfterCounter returns a count of finished PostRepositoryMock.List invocations
func (mmList *PostRepositoryMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of PostRepositoryMock.List invocations
func (mmList *PostRepositoryMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to PostRepositoryMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mPostRepositoryMockList) Calls() []*PostRepositoryMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*PostRepositoryMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *PostRepositoryMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *PostRepositoryMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostRepositoryMock.List at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostRepositoryMock.List at\n%s", m.ListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostRepositoryMock.List at\n%s with params: %#v", m.ListMock.defaultExpectation.expectationOrigins.origin, *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Errorf("Expected call to PostRepositoryMock.List at\n%s", m.funcListOrigin)
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to PostRepositoryMock.List at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), m.ListMock.expectedInvocationsOrigin, afterListCounter)
	}
}

type mPostRepositoryMockUpdateCommentsAvailability struct {
	optional           bool
	mock               *PostRepositoryMock
	defaultExpectation *PostRepositoryMockUpdateCommentsAvailabilityExpectation
	expectations       []*PostRepositoryMockUpdateCommentsAvailabilityExpectation

	callArgs []*PostRepositoryMockUpdateCommentsAvailabilityParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostRepositoryMockUpdateCommentsAvailabilityExpectation specifies expectation struct of the PostRepository.UpdateCommentsAvailability
type PostRepositoryMockUpdateCommentsAvailabilityExpectation struct {
	mock               *PostRepositoryMock
	params             *PostRepositoryMockUpdateCommentsAvailabilityParams
	paramPtrs          *PostRepositoryMockUpdateCommentsAvailabilityParamPtrs
	expectationOrigins PostRepositoryMockUpdateCommentsAvailabilityExpectationOrigins
	results            *PostRepositoryMockUpdateCommentsAvailabilityResults
	returnOrigin       string
	Counter            uint64
}

// PostRepositoryMockUpdateCommentsAvailabilityParams contains parameters of the PostRepository.UpdateCommentsAvailability
type PostRepositoryMockUpdateCommentsAvailabilityParams struct {
	ctx     context.Context
	postID  int64
	enabled bool
}

// PostRepositoryMockUpdateCommentsAvailabilityParamPtrs contains pointers to parameters of the PostRepository.UpdateCommentsAvailability
type PostRepositoryMockUpdateCommentsAvailabilityParamPtrs struct {
	ctx     *context.Context
	postID  *int64
	enabled *bool
}

// PostRepositoryMockUpdateCommentsAvailabilityResults contains results of the PostRepository.UpdateCommentsAvailability
type PostRepositoryMockUpdateCommentsAvailabilityResults struct {
	p1  model.Post
	err error
}

// PostRepositoryMockUpdateCommentsAvailabilityOrigins contains origins of expectations of the PostRepository.UpdateCommentsAvailability
type PostRepositoryMockUpdateCommentsAvailabilityExpectationOrigins struct {
	origin        string
	originCtx     string
	originPostID  string
	originEnabled string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Optional() *mPostRepositoryMockUpdateCommentsAvailability {
	mmUpdateCommentsAvailability.optional = true
	return mmUpdateCommentsAvailability
}

// Expect sets up expected params for PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Expect(ctx context.Context, postID int64, enabled bool) *mPostRepositoryMockUpdateCommentsAvailability {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	if mmUpdateCommentsAvailability.defaultExpectation == nil {
		mmUpdateCommentsAvailability.defaultExpectation = &PostRepositoryMockUpdateCommentsAvailabilityExpectation{}
	}

	if mmUpdateCommentsAvailability.defaultExpectation.paramPtrs != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by ExpectParams functions")
	}

	mmUpdateCommentsAvailability.defaultExpectation.params = &PostRepositoryMockUpdateCommentsAvailabilityParams{ctx, postID, enabled}
	mmUpdateCommentsAvailability.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateCommentsAvailability.expectations {
		if minimock.Equal(e.params, mmUpdateCommentsAvailability.defaultExpectation.params) {
			mmUpdateCommentsAvailability.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateCommentsAvailability.defaultExpectation.params)
		}
	}

	return mmUpdateCommentsAvailability
}

// ExpectCtxParam1 sets up expected param ctx for PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) ExpectCtxParam1(ctx context.Context) *mPostRepositoryMockUpdateCommentsAvailability {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	if mmUpdateCommentsAvailability.defaultExpectation == nil {
		mmUpdateCommentsAvailability.defaultExpectation = &PostRepositoryMockUpdateCommentsAvailabilityExpectation{}
	}

	if mmUpdateCommentsAvailability.defaultExpectation.params != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Expect")
	}

	if mmUpdateCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmUpdateCommentsAvailability.defaultExpectation.paramPtrs = &PostRepositoryMockUpdateCommentsAvailabilityParamPtrs{}
	}
	mmUpdateCommentsAvailability.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateCommentsAvailability.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateCommentsAvailability
}

// ExpectPostIDParam2 sets up expected param postID for PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) ExpectPostIDParam2(postID int64) *mPostRepositoryMockUpdateCommentsAvailability {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	if mmUpdateCommentsAvailability.defaultExpectation == nil {
		mmUpdateCommentsAvailability.defaultExpectation = &PostRepositoryMockUpdateCommentsAvailabilityExpectation{}
	}

	if mmUpdateCommentsAvailability.defaultExpectation.params != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Expect")
	}

	if mmUpdateCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmUpdateCommentsAvailability.defaultExpectation.paramPtrs = &PostRepositoryMockUpdateCommentsAvailabilityParamPtrs{}
	}
	mmUpdateCommentsAvailability.defaultExpectation.paramPtrs.postID = &postID
	mmUpdateCommentsAvailability.defaultExpectation.expectationOrigins.originPostID = minimock.CallerInfo(1)

	return mmUpdateCommentsAvailability
}

// ExpectEnabledParam3 sets up expected param enabled for PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) ExpectEnabledParam3(enabled bool) *mPostRepositoryMockUpdateCommentsAvailability {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	if mmUpdateCommentsAvailability.defaultExpectation == nil {
		mmUpdateCommentsAvailability.defaultExpectation = &PostRepositoryMockUpdateCommentsAvailabilityExpectation{}
	}

	if mmUpdateCommentsAvailability.defaultExpectation.params != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Expect")
	}

	if mmUpdateCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmUpdateCommentsAvailability.defaultExpectation.paramPtrs = &PostRepositoryMockUpdateCommentsAvailabilityParamPtrs{}
	}
	mmUpdateCommentsAvailability.defaultExpectation.paramPtrs.enabled = &enabled
	mmUpdateCommentsAvailability.defaultExpectation.expectationOrigins.originEnabled = minimock.CallerInfo(1)

	return mmUpdateCommentsAvailability
}

// Inspect accepts an inspector function that has same arguments as the PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Inspect(f func(ctx context.Context, postID int64, enabled bool)) *mPostRepositoryMockUpdateCommentsAvailability {
	if mmUpdateCommentsAvailability.mock.inspectFuncUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("Inspect function is already set for PostRepositoryMock.UpdateCommentsAvailability")
	}

	mmUpdateCommentsAvailability.mock.inspectFuncUpdateCommentsAvailability = f

	return mmUpdateCommentsAvailability
}

// Return sets up results that will be returned by PostRepository.UpdateCommentsAvailability
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Return(p1 model.Post, err error) *PostRepositoryMock {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	if mmUpdateCommentsAvailability.defaultExpectation == nil {
		mmUpdateCommentsAvailability.defaultExpectation = &PostRepositoryMockUpdateCommentsAvailabilityExpectation{mock: mmUpdateCommentsAvailability.mock}
	}
	mmUpdateCommentsAvailability.defaultExpectation.results = &PostRepositoryMockUpdateCommentsAvailabilityResults{p1, err}
	mmUpdateCommentsAvailability.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateCommentsAvailability.mock
}

// Set uses given function f to mock the PostRepository.UpdateCommentsAvailability method
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Set(f func(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error)) *PostRepositoryMock {
	if mmUpdateCommentsAvailability.defaultExpectation != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("Default expectation is already set for the PostRepository.UpdateCommentsAvailability method")
	}

	if len(mmUpdateCommentsAvailability.expectations) > 0 {
		mmUpdateCommentsAvailability.mock.t.Fatalf("Some expectations are already set for the PostRepository.UpdateCommentsAvailability method")
	}

	mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability = f
	mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailabilityOrigin = minimock.CallerInfo(1)
	return mmUpdateCommentsAvailability.mock
}

// When sets expectation for the PostRepository.UpdateCommentsAvailability which will trigger the result defined by the following
// Then helper
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) When(ctx context.Context, postID int64, enabled bool) *PostRepositoryMockUpdateCommentsAvailabilityExpectation {
	if mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.mock.t.Fatalf("PostRepositoryMock.UpdateCommentsAvailability mock is already set by Set")
	}

	expectation := &PostRepositoryMockUpdateCommentsAvailabilityExpectation{
		mock:               mmUpdateCommentsAvailability.mock,
		params:             &PostRepositoryMockUpdateCommentsAvailabilityParams{ctx, postID, enabled},
		expectationOrigins: PostRepositoryMockUpdateCommentsAvailabilityExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateCommentsAvailability.expectations = append(mmUpdateCommentsAvailability.expectations, expectation)
	return expectation
}

// Then sets up PostRepository.UpdateCommentsAvailability return parameters for the expectation previously defined by the When method
func (e *PostRepositoryMockUpdateCommentsAvailabilityExpectation) Then(p1 model.Post, err error) *PostRepositoryMock {
	e.results = &PostRepositoryMockUpdateCommentsAvailabilityResults{p1, err}
	return e.mock
}

// Times sets number of times PostRepository.UpdateCommentsAvailability should be invoked
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Times(n uint64) *mPostRepositoryMockUpdateCommentsAvailability {
	if n == 0 {
		mmUpdateCommentsAvailability.mock.t.Fatalf("Times of PostRepositoryMock.UpdateCommentsAvailability mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateCommentsAvailability.expectedInvocations, n)
	mmUpdateCommentsAvailability.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateCommentsAvailability
}

func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) invocationsDone() bool {
	if len(mmUpdateCommentsAvailability.expectations) == 0 && mmUpdateCommentsAvailability.defaultExpectation == nil && mmUpdateCommentsAvailability.mock.funcUpdateCommentsAvailability == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateCommentsAvailability.mock.afterUpdateCommentsAvailabilityCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateCommentsAvailability.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateCommentsAvailability implements mm_usecase.PostRepository
func (mmUpdateCommentsAvailability *PostRepositoryMock) UpdateCommentsAvailability(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmUpdateCommentsAvailability.beforeUpdateCommentsAvailabilityCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateCommentsAvailability.afterUpdateCommentsAvailabilityCounter, 1)

	mmUpdateCommentsAvailability.t.Helper()

	if mmUpdateCommentsAvailability.inspectFuncUpdateCommentsAvailability != nil {
		mmUpdateCommentsAvailability.inspectFuncUpdateCommentsAvailability(ctx, postID, enabled)
	}

	mm_params := PostRepositoryMockUpdateCommentsAvailabilityParams{ctx, postID, enabled}

	// Record call args
	mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.mutex.Lock()
	mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.callArgs = append(mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.callArgs, &mm_params)
	mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.mutex.Unlock()

	for _, e := range mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.paramPtrs

		mm_got := PostRepositoryMockUpdateCommentsAvailabilityParams{ctx, postID, enabled}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateCommentsAvailability.t.Errorf("PostRepositoryMock.UpdateCommentsAvailability got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.postID != nil && !minimock.Equal(*mm_want_ptrs.postID, mm_got.postID) {
				mmUpdateCommentsAvailability.t.Errorf("PostRepositoryMock.UpdateCommentsAvailability got unexpected parameter postID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originPostID, *mm_want_ptrs.postID, mm_got.postID, minimock.Diff(*mm_want_ptrs.postID, mm_got.postID))
			}

			if mm_want_ptrs.enabled != nil && !minimock.Equal(*mm_want_ptrs.enabled, mm_got.enabled) {
				mmUpdateCommentsAvailability.t.Errorf("PostRepositoryMock.UpdateCommentsAvailability got unexpected parameter enabled, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originEnabled, *mm_want_ptrs.enabled, mm_got.enabled, minimock.Diff(*mm_want_ptrs.enabled, mm_got.enabled))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateCommentsAvailability.t.Errorf("PostRepositoryMock.UpdateCommentsAvailability got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateCommentsAvailability.UpdateCommentsAvailabilityMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateCommentsAvailability.t.Fatal("No results are set for the PostRepositoryMock.UpdateCommentsAvailability")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmUpdateCommentsAvailability.funcUpdateCommentsAvailability != nil {
		return mmUpdateCommentsAvailability.funcUpdateCommentsAvailability(ctx, postID, enabled)
	}
	mmUpdateCommentsAvailability.t.Fatalf("Unexpected call to PostRepositoryMock.UpdateCommentsAvailability. %v %v %v", ctx, postID, enabled)
	return
}

// UpdateCommentsAvailabilityAfterCounter returns a count of finished PostRepositoryMock.UpdateCommentsAvailability invocations
func (mmUpdateCommentsAvailability *PostRepositoryMock) UpdateCommentsAvailabilityAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCommentsAvailability.afterUpdateCommentsAvailabilityCounter)
}

// UpdateCommentsAvailabilityBeforeCounter returns a count of PostRepositoryMock.UpdateCommentsAvailability invocations
func (mmUpdateCommentsAvailability *PostRepositoryMock) UpdateCommentsAvailabilityBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateCommentsAvailability.beforeUpdateCommentsAvailabilityCounter)
}

// Calls returns a list of arguments used in each call to PostRepositoryMock.UpdateCommentsAvailability.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateCommentsAvailability *mPostRepositoryMockUpdateCommentsAvailability) Calls() []*PostRepositoryMockUpdateCommentsAvailabilityParams {
	mmUpdateCommentsAvailability.mutex.RLock()

	argCopy := make([]*PostRepositoryMockUpdateCommentsAvailabilityParams, len(mmUpdateCommentsAvailability.callArgs))
	copy(argCopy, mmUpdateCommentsAvailability.callArgs)

	mmUpdateCommentsAvailability.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateCommentsAvailabilityDone returns true if the count of the UpdateCommentsAvailability invocations corresponds
// the number of defined expectations
func (m *PostRepositoryMock) MinimockUpdateCommentsAvailabilityDone() bool {
	if m.UpdateCommentsAvailabilityMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateCommentsAvailabilityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateCommentsAvailabilityMock.invocationsDone()
}

// MinimockUpdateCommentsAvailabilityInspect logs each unmet expectation
func (m *PostRepositoryMock) MinimockUpdateCommentsAvailabilityInspect() {
	for _, e := range m.UpdateCommentsAvailabilityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostRepositoryMock.UpdateCommentsAvailability at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCommentsAvailabilityCounter := mm_atomic.LoadUint64(&m.afterUpdateCommentsAvailabilityCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateCommentsAvailabilityMock.defaultExpectation != nil && afterUpdateCommentsAvailabilityCounter < 1 {
		if m.UpdateCommentsAvailabilityMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostRepositoryMock.UpdateCommentsAvailability at\n%s", m.UpdateCommentsAvailabilityMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostRepositoryMock.UpdateCommentsAvailability at\n%s with params: %#v", m.UpdateCommentsAvailabilityMock.defaultExpectation.expectationOrigins.origin, *m.UpdateCommentsAvailabilityMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateCommentsAvailability != nil && afterUpdateCommentsAvailabilityCounter < 1 {
		m.t.Errorf("Expected call to PostRepositoryMock.UpdateCommentsAvailability at\n%s", m.funcUpdateCommentsAvailabilityOrigin)
	}

	if !m.UpdateCommentsAvailabilityMock.invocationsDone() && afterUpdateCommentsAvailabilityCounter > 0 {
		m.t.Errorf("Expected %d calls to PostRepositoryMock.UpdateCommentsAvailability at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateCommentsAvailabilityMock.expectedInvocations), m.UpdateCommentsAvailabilityMock.expectedInvocationsOrigin, afterUpdateCommentsAvailabilityCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PostRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByIDInspect()

			m.MinimockListInspect()

			m.MinimockUpdateCommentsAvailabilityInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PostRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PostRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockListDone() &&
		m.MinimockUpdateCommentsAvailabilityDone()
}
