// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-grapql-service/internal/delivery/graphql.CommentUsecase -o comment_usecase_mock.go -n CommentUsecaseMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-grapql-service/internal/model"
)

// CommentUsecaseMock implements mm_graphql.CommentUsecase
type CommentUsecaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateComment          func(ctx context.Context, userUUID string, postID int64, parentID *int64, content string) (c2 model.Comment, err error)
	funcCreateCommentOrigin    string
	inspectFuncCreateComment   func(ctx context.Context, userUUID string, postID int64, parentID *int64, content string)
	afterCreateCommentCounter  uint64
	beforeCreateCommentCounter uint64
	CreateCommentMock          mCommentUsecaseMockCreateComment

	funcListComments          func(ctx context.Context, filter model.CommentListFilter) (c2 model.CommentConnection, err error)
	funcListCommentsOrigin    string
	inspectFuncListComments   func(ctx context.Context, filter model.CommentListFilter)
	afterListCommentsCounter  uint64
	beforeListCommentsCounter uint64
	ListCommentsMock          mCommentUsecaseMockListComments
}

// NewCommentUsecaseMock returns a mock for mm_graphql.CommentUsecase
func NewCommentUsecaseMock(t minimock.Tester) *CommentUsecaseMock {
	m := &CommentUsecaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateCommentMock = mCommentUsecaseMockCreateComment{mock: m}
	m.CreateCommentMock.callArgs = []*CommentUsecaseMockCreateCommentParams{}

	m.ListCommentsMock = mCommentUsecaseMockListComments{mock: m}
	m.ListCommentsMock.callArgs = []*CommentUsecaseMockListCommentsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCommentUsecaseMockCreateComment struct {
	optional           bool
	mock               *CommentUsecaseMock
	defaultExpectation *CommentUsecaseMockCreateCommentExpectation
	expectations       []*CommentUsecaseMockCreateCommentExpectation

	callArgs []*CommentUsecaseMockCreateCommentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentUsecaseMockCreateCommentExpectation specifies expectation struct of the CommentUsecase.CreateComment
type CommentUsecaseMockCreateCommentExpectation struct {
	mock               *CommentUsecaseMock
	params             *CommentUsecaseMockCreateCommentParams
	paramPtrs          *CommentUsecaseMockCreateCommentParamPtrs
	expectationOrigins CommentUsecaseMockCreateCommentExpectationOrigins
	results            *CommentUsecaseMockCreateCommentResults
	returnOrigin       string
	Counter            uint64
}

// CommentUsecaseMockCreateCommentParams contains parameters of the CommentUsecase.CreateComment
type CommentUsecaseMockCreateCommentParams struct {
	ctx      context.Context
	userUUID string
	postID   int64
	parentID *int64
	content  string
}

// CommentUsecaseMockCreateCommentParamPtrs contains pointers to parameters of the CommentUsecase.CreateComment
type CommentUsecaseMockCreateCommentParamPtrs struct {
	ctx      *context.Context
	userUUID *string
	postID   *int64
	parentID **int64
	content  *string
}

// CommentUsecaseMockCreateCommentResults contains results of the CommentUsecase.CreateComment
type CommentUsecaseMockCreateCommentResults struct {
	c2  model.Comment
	err error
}

// CommentUsecaseMockCreateCommentOrigins contains origins of expectations of the CommentUsecase.CreateComment
type CommentUsecaseMockCreateCommentExpectationOrigins struct {
	origin         string
	originCtx      string
	originUserUUID string
	originPostID   string
	originParentID string
	originContent  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateComment *mCommentUsecaseMockCreateComment) Optional() *mCommentUsecaseMockCreateComment {
	mmCreateComment.optional = true
	return mmCreateComment
}

// Expect sets up expected params for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) Expect(ctx context.Context, userUUID string, postID int64, parentID *int64, content string) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.paramPtrs != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by ExpectParams functions")
	}

	mmCreateComment.defaultExpectation.params = &CommentUsecaseMockCreateCommentParams{ctx, userUUID, postID, parentID, content}
	mmCreateComment.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateComment.expectations {
		if minimock.Equal(e.params, mmCreateComment.defaultExpectation.params) {
			mmCreateComment.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateComment.defaultExpectation.params)
		}
	}

	return mmCreateComment
}

// ExpectCtxParam1 sets up expected param ctx for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) ExpectCtxParam1(ctx context.Context) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.params != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Expect")
	}

	if mmCreateComment.defaultExpectation.paramPtrs == nil {
		mmCreateComment.defaultExpectation.paramPtrs = &CommentUsecaseMockCreateCommentParamPtrs{}
	}
	mmCreateComment.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateComment.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateComment
}

// ExpectUserUUIDParam2 sets up expected param userUUID for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) ExpectUserUUIDParam2(userUUID string) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.params != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Expect")
	}

	if mmCreateComment.defaultExpectation.paramPtrs == nil {
		mmCreateComment.defaultExpectation.paramPtrs = &CommentUsecaseMockCreateCommentParamPtrs{}
	}
	mmCreateComment.defaultExpectation.paramPtrs.userUUID = &userUUID
	mmCreateComment.defaultExpectation.expectationOrigins.originUserUUID = minimock.CallerInfo(1)

	return mmCreateComment
}

// ExpectPostIDParam3 sets up expected param postID for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) ExpectPostIDParam3(postID int64) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.params != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Expect")
	}

	if mmCreateComment.defaultExpectation.paramPtrs == nil {
		mmCreateComment.defaultExpectation.paramPtrs = &CommentUsecaseMockCreateCommentParamPtrs{}
	}
	mmCreateComment.defaultExpectation.paramPtrs.postID = &postID
	mmCreateComment.defaultExpectation.expectationOrigins.originPostID = minimock.CallerInfo(1)

	return mmCreateComment
}

// ExpectParentIDParam4 sets up expected param parentID for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) ExpectParentIDParam4(parentID *int64) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.params != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Expect")
	}

	if mmCreateComment.defaultExpectation.paramPtrs == nil {
		mmCreateComment.defaultExpectation.paramPtrs = &CommentUsecaseMockCreateCommentParamPtrs{}
	}
	mmCreateComment.defaultExpectation.paramPtrs.parentID = &parentID
	mmCreateComment.defaultExpectation.expectationOrigins.originParentID = minimock.CallerInfo(1)

	return mmCreateComment
}

// ExpectContentParam5 sets up expected param content for CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) ExpectContentParam5(content string) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{}
	}

	if mmCreateComment.defaultExpectation.params != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Expect")
	}

	if mmCreateComment.defaultExpectation.paramPtrs == nil {
		mmCreateComment.defaultExpectation.paramPtrs = &CommentUsecaseMockCreateCommentParamPtrs{}
	}
	mmCreateComment.defaultExpectation.paramPtrs.content = &content
	mmCreateComment.defaultExpectation.expectationOrigins.originContent = minimock.CallerInfo(1)

	return mmCreateComment
}

// Inspect accepts an inspector function that has same arguments as the CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) Inspect(f func(ctx context.Context, userUUID string, postID int64, parentID *int64, content string)) *mCommentUsecaseMockCreateComment {
	if mmCreateComment.mock.inspectFuncCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("Inspect function is already set for CommentUsecaseMock.CreateComment")
	}

	mmCreateComment.mock.inspectFuncCreateComment = f

	return mmCreateComment
}

// Return sets up results that will be returned by CommentUsecase.CreateComment
func (mmCreateComment *mCommentUsecaseMockCreateComment) Return(c2 model.Comment, err error) *CommentUsecaseMock {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	if mmCreateComment.defaultExpectation == nil {
		mmCreateComment.defaultExpectation = &CommentUsecaseMockCreateCommentExpectation{mock: mmCreateComment.mock}
	}
	mmCreateComment.defaultExpectation.results = &CommentUsecaseMockCreateCommentResults{c2, err}
	mmCreateComment.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateComment.mock
}

// Set uses given function f to mock the CommentUsecase.CreateComment method
func (mmCreateComment *mCommentUsecaseMockCreateComment) Set(f func(ctx context.Context, userUUID string, postID int64, parentID *int64, content string) (c2 model.Comment, err error)) *CommentUsecaseMock {
	if mmCreateComment.defaultExpectation != nil {
		mmCreateComment.mock.t.Fatalf("Default expectation is already set for the CommentUsecase.CreateComment method")
	}

	if len(mmCreateComment.expectations) > 0 {
		mmCreateComment.mock.t.Fatalf("Some expectations are already set for the CommentUsecase.CreateComment method")
	}

	mmCreateComment.mock.funcCreateComment = f
	mmCreateComment.mock.funcCreateCommentOrigin = minimock.CallerInfo(1)
	return mmCreateComment.mock
}

// When sets expectation for the CommentUsecase.CreateComment which will trigger the result defined by the following
// Then helper
func (mmCreateComment *mCommentUsecaseMockCreateComment) When(ctx context.Context, userUUID string, postID int64, parentID *int64, content string) *CommentUsecaseMockCreateCommentExpectation {
	if mmCreateComment.mock.funcCreateComment != nil {
		mmCreateComment.mock.t.Fatalf("CommentUsecaseMock.CreateComment mock is already set by Set")
	}

	expectation := &CommentUsecaseMockCreateCommentExpectation{
		mock:               mmCreateComment.mock,
		params:             &CommentUsecaseMockCreateCommentParams{ctx, userUUID, postID, parentID, content},
		expectationOrigins: CommentUsecaseMockCreateCommentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateComment.expectations = append(mmCreateComment.expectations, expectation)
	return expectation
}

// Then sets up CommentUsecase.CreateComment return parameters for the expectation previously defined by the When method
func (e *CommentUsecaseMockCreateCommentExpectation) Then(c2 model.Comment, err error) *CommentUsecaseMock {
	e.results = &CommentUsecaseMockCreateCommentResults{c2, err}
	return e.mock
}

// Times sets number of times CommentUsecase.CreateComment should be invoked
func (mmCreateComment *mCommentUsecaseMockCreateComment) Times(n uint64) *mCommentUsecaseMockCreateComment {
	if n == 0 {
		mmCreateComment.mock.t.Fatalf("Times of CommentUsecaseMock.CreateComment mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateComment.expectedInvocations, n)
	mmCreateComment.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateComment
}

func (mmCreateComment *mCommentUsecaseMockCreateComment) invocationsDone() bool {
	if len(mmCreateComment.expectations) == 0 && mmCreateComment.defaultExpectation == nil && mmCreateComment.mock.funcCreateComment == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateComment.mock.afterCreateCommentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateComment.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateComment implements mm_graphql.CommentUsecase
func (mmCreateComment *CommentUsecaseMock) CreateComment(ctx context.Context, userUUID string, postID int64, parentID *int64, content string) (c2 model.Comment, err error) {
	mm_atomic.AddUint64(&mmCreateComment.beforeCreateCommentCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateComment.afterCreateCommentCounter, 1)

	mmCreateComment.t.Helper()

	if mmCreateComment.inspectFuncCreateComment != nil {
		mmCreateComment.inspectFuncCreateComment(ctx, userUUID, postID, parentID, content)
	}

	mm_params := CommentUsecaseMockCreateCommentParams{ctx, userUUID, postID, parentID, content}

	// Record call args
	mmCreateComment.CreateCommentMock.mutex.Lock()
	mmCreateComment.CreateCommentMock.callArgs = append(mmCreateComment.CreateCommentMock.callArgs, &mm_params)
	mmCreateComment.CreateCommentMock.mutex.Unlock()

	for _, e := range mmCreateComment.CreateCommentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmCreateComment.CreateCommentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateComment.CreateCommentMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateComment.CreateCommentMock.defaultExpectation.params
		mm_want_ptrs := mmCreateComment.CreateCommentMock.defaultExpectation.paramPtrs

		mm_got := CommentUsecaseMockCreateCommentParams{ctx, userUUID, postID, parentID, content}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userUUID != nil && !minimock.Equal(*mm_want_ptrs.userUUID, mm_got.userUUID) {
				mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameter userUUID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.originUserUUID, *mm_want_ptrs.userUUID, mm_got.userUUID, minimock.Diff(*mm_want_ptrs.userUUID, mm_got.userUUID))
			}

			if mm_want_ptrs.postID != nil && !minimock.Equal(*mm_want_ptrs.postID, mm_got.postID) {
				mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameter postID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.originPostID, *mm_want_ptrs.postID, mm_got.postID, minimock.Diff(*mm_want_ptrs.postID, mm_got.postID))
			}

			if mm_want_ptrs.parentID != nil && !minimock.Equal(*mm_want_ptrs.parentID, mm_got.parentID) {
				mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameter parentID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.originParentID, *mm_want_ptrs.parentID, mm_got.parentID, minimock.Diff(*mm_want_ptrs.parentID, mm_got.parentID))
			}

			if mm_want_ptrs.content != nil && !minimock.Equal(*mm_want_ptrs.content, mm_got.content) {
				mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameter content, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.originContent, *mm_want_ptrs.content, mm_got.content, minimock.Diff(*mm_want_ptrs.content, mm_got.content))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateComment.t.Errorf("CommentUsecaseMock.CreateComment got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateComment.CreateCommentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateComment.CreateCommentMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateComment.t.Fatal("No results are set for the CommentUsecaseMock.CreateComment")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmCreateComment.funcCreateComment != nil {
		return mmCreateComment.funcCreateComment(ctx, userUUID, postID, parentID, content)
	}
	mmCreateComment.t.Fatalf("Unexpected call to CommentUsecaseMock.CreateComment. %v %v %v %v %v", ctx, userUUID, postID, parentID, content)
	return
}

// CreateCommentAfterCounter returns a count of finished CommentUsecaseMock.CreateComment invocations
func (mmCreateComment *CommentUsecaseMock) CreateCommentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateComment.afterCreateCommentCounter)
}

// CreateCommentBeforeCounter returns a count of CommentUsecaseMock.CreateComment invocations
func (mmCreateComment *CommentUsecaseMock) CreateCommentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateComment.beforeCreateCommentCounter)
}

// Calls returns a list of arguments used in each call to CommentUsecaseMock.CreateComment.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateComment *mCommentUsecaseMockCreateComment) Calls() []*CommentUsecaseMockCreateCommentParams {
	mmCreateComment.mutex.RLock()

	argCopy := make([]*CommentUsecaseMockCreateCommentParams, len(mmCreateComment.callArgs))
	copy(argCopy, mmCreateComment.callArgs)

	mmCreateComment.mutex.RUnlock()

	return argCopy
}

// MinimockCreateCommentDone returns true if the count of the CreateComment invocations corresponds
// the number of defined expectations
func (m *CommentUsecaseMock) MinimockCreateCommentDone() bool {
	if m.CreateCommentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateCommentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateCommentMock.invocationsDone()
}

// MinimockCreateCommentInspect logs each unmet expectation
func (m *CommentUsecaseMock) MinimockCreateCommentInspect() {
	for _, e := range m.CreateCommentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentUsecaseMock.CreateComment at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCommentCounter := mm_atomic.LoadUint64(&m.afterCreateCommentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateCommentMock.defaultExpectation != nil && afterCreateCommentCounter < 1 {
		if m.CreateCommentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentUsecaseMock.CreateComment at\n%s", m.CreateCommentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentUsecaseMock.CreateComment at\n%s with params: %#v", m.CreateCommentMock.defaultExpectation.expectationOrigins.origin, *m.CreateCommentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateComment != nil && afterCreateCommentCounter < 1 {
		m.t.Errorf("Expected call to CommentUsecaseMock.CreateComment at\n%s", m.funcCreateCommentOrigin)
	}

	if !m.CreateCommentMock.invocationsDone() && afterCreateCommentCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentUsecaseMock.CreateComment at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateCommentMock.expectedInvocations), m.CreateCommentMock.expectedInvocationsOrigin, afterCreateCommentCounter)
	}
}

type mCommentUsecaseMockListComments struct {
	optional           bool
	mock               *CommentUsecaseMock
	defaultExpectation *CommentUsecaseMockListCommentsExpectation
	expectations       []*CommentUsecaseMockListCommentsExpectation

	callArgs []*CommentUsecaseMockListCommentsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentUsecaseMockListCommentsExpectation specifies expectation struct of the CommentUsecase.ListComments
type CommentUsecaseMockListCommentsExpectation struct {
	mock               *CommentUsecaseMock
	params             *CommentUsecaseMockListCommentsParams
	paramPtrs          *CommentUsecaseMockListCommentsParamPtrs
	expectationOrigins CommentUsecaseMockListCommentsExpectationOrigins
	results            *CommentUsecaseMockListCommentsResults
	returnOrigin       string
	Counter            uint64
}

// CommentUsecaseMockListCommentsParams contains parameters of the CommentUsecase.ListComments
type CommentUsecaseMockListCommentsParams struct {
	ctx    context.Context
	filter model.CommentListFilter
}

// CommentUsecaseMockListCommentsParamPtrs contains pointers to parameters of the CommentUsecase.ListComments
type CommentUsecaseMockListCommentsParamPtrs struct {
	ctx    *context.Context
	filter *model.CommentListFilter
}

// CommentUsecaseMockListCommentsResults contains results of the CommentUsecase.ListComments
type CommentUsecaseMockListCommentsResults struct {
	c2  model.CommentConnection
	err error
}

// CommentUsecaseMockListCommentsOrigins contains origins of expectations of the CommentUsecase.ListComments
type CommentUsecaseMockListCommentsExpectationOrigins struct {
	origin       string
	originCtx    string
	originFilter string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListComments *mCommentUsecaseMockListComments) Optional() *mCommentUsecaseMockListComments {
	mmListComments.optional = true
	return mmListComments
}

// Expect sets up expected params for CommentUsecase.ListComments
func (mmListComments *mCommentUsecaseMockListComments) Expect(ctx context.Context, filter model.CommentListFilter) *mCommentUsecaseMockListComments {
	if mmListComments.mock.funcListComments != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Set")
	}

	if mmListComments.defaultExpectation == nil {
		mmListComments.defaultExpectation = &CommentUsecaseMockListCommentsExpectation{}
	}

	if mmListComments.defaultExpectation.paramPtrs != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by ExpectParams functions")
	}

	mmListComments.defaultExpectation.params = &CommentUsecaseMockListCommentsParams{ctx, filter}
	mmListComments.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListComments.expectations {
		if minimock.Equal(e.params, mmListComments.defaultExpectation.params) {
			mmListComments.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListComments.defaultExpectation.params)
		}
	}

	return mmListComments
}

// ExpectCtxParam1 sets up expected param ctx for CommentUsecase.ListComments
func (mmListComments *mCommentUsecaseMockListComments) ExpectCtxParam1(ctx context.Context) *mCommentUsecaseMockListComments {
	if mmListComments.mock.funcListComments != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Set")
	}

	if mmListComments.defaultExpectation == nil {
		mmListComments.defaultExpectation = &CommentUsecaseMockListCommentsExpectation{}
	}

	if mmListComments.defaultExpectation.params != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Expect")
	}

	if mmListComments.defaultExpectation.paramPtrs == nil {
		mmListComments.defaultExpectation.paramPtrs = &CommentUsecaseMockListCommentsParamPtrs{}
	}
	mmListComments.defaultExpectation.paramPtrs.ctx = &ctx
	mmListComments.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListComments
}

// ExpectFilterParam2 sets up expected param filter for CommentUsecase.ListComments
func (mmListComments *mCommentUsecaseMockListComments) ExpectFilterParam2(filter model.CommentListFilter) *mCommentUsecaseMockListComments {
	if mmListComments.mock.funcListComments != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Set")
	}

	if mmListComments.defaultExpectation == nil {
		mmListComments.defaultExpectation = &CommentUsecaseMockListCommentsExpectation{}
	}

	if mmListComments.defaultExpectation.params != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Expect")
	}

	if mmListComments.defaultExpectation.paramPtrs == nil {
		mmListComments.defaultExpectation.paramPtrs = &CommentUsecaseMockListCommentsParamPtrs{}
	}
	mmListComments.defaultExpectation.paramPtrs.filter = &filter
	mmListComments.defaultExpectation.expectationOrigins.originFilter = minimock.CallerInfo(1)

	return mmListComments
}

// Inspect accepts an inspector function that has same arguments as the CommentUsecase.ListComments
func (mmListComments *mCommentUsecaseMockListComments) Inspect(f func(ctx context.Context, filter model.CommentListFilter)) *mCommentUsecaseMockListComments {
	if mmListComments.mock.inspectFuncListComments != nil {
		mmListComments.mock.t.Fatalf("Inspect function is already set for CommentUsecaseMock.ListComments")
	}

	mmListComments.mock.inspectFuncListComments = f

	return mmListComments
}

// Return sets up results that will be returned by CommentUsecase.ListComments
func (mmListComments *mCommentUsecaseMockListComments) Return(c2 model.CommentConnection, err error) *CommentUsecaseMock {
	if mmListComments.mock.funcListComments != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Set")
	}

	if mmListComments.defaultExpectation == nil {
		mmListComments.defaultExpectation = &CommentUsecaseMockListCommentsExpectation{mock: mmListComments.mock}
	}
	mmListComments.defaultExpectation.results = &CommentUsecaseMockListCommentsResults{c2, err}
	mmListComments.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListComments.mock
}

// Set uses given function f to mock the CommentUsecase.ListComments method
func (mmListComments *mCommentUsecaseMockListComments) Set(f func(ctx context.Context, filter model.CommentListFilter) (c2 model.CommentConnection, err error)) *CommentUsecaseMock {
	if mmListComments.defaultExpectation != nil {
		mmListComments.mock.t.Fatalf("Default expectation is already set for the CommentUsecase.ListComments method")
	}

	if len(mmListComments.expectations) > 0 {
		mmListComments.mock.t.Fatalf("Some expectations are already set for the CommentUsecase.ListComments method")
	}

	mmListComments.mock.funcListComments = f
	mmListComments.mock.funcListCommentsOrigin = minimock.CallerInfo(1)
	return mmListComments.mock
}

// When sets expectation for the CommentUsecase.ListComments which will trigger the result defined by the following
// Then helper
func (mmListComments *mCommentUsecaseMockListComments) When(ctx context.Context, filter model.CommentListFilter) *CommentUsecaseMockListCommentsExpectation {
	if mmListComments.mock.funcListComments != nil {
		mmListComments.mock.t.Fatalf("CommentUsecaseMock.ListComments mock is already set by Set")
	}

	expectation := &CommentUsecaseMockListCommentsExpectation{
		mock:               mmListComments.mock,
		params:             &CommentUsecaseMockListCommentsParams{ctx, filter},
		expectationOrigins: CommentUsecaseMockListCommentsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListComments.expectations = append(mmListComments.expectations, expectation)
	return expectation
}

// Then sets up CommentUsecase.ListComments return parameters for the expectation previously defined by the When method
func (e *CommentUsecaseMockListCommentsExpectation) Then(c2 model.CommentConnection, err error) *CommentUsecaseMock {
	e.results = &CommentUsecaseMockListCommentsResults{c2, err}
	return e.mock
}

// Times sets number of times CommentUsecase.ListComments should be invoked
func (mmListComments *mCommentUsecaseMockListComments) Times(n uint64) *mCommentUsecaseMockListComments {
	if n == 0 {
		mmListComments.mock.t.Fatalf("Times of CommentUsecaseMock.ListComments mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListComments.expectedInvocations, n)
	mmListComments.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListComments
}

func (mmListComments *mCommentUsecaseMockListComments) invocationsDone() bool {
	if len(mmListComments.expectations) == 0 && mmListComments.defaultExpectation == nil && mmListComments.mock.funcListComments == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListComments.mock.afterListCommentsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListComments.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListComments implements mm_graphql.CommentUsecase
func (mmListComments *CommentUsecaseMock) ListComments(ctx context.Context, filter model.CommentListFilter) (c2 model.CommentConnection, err error) {
	mm_atomic.AddUint64(&mmListComments.beforeListCommentsCounter, 1)
	defer mm_atomic.AddUint64(&mmListComments.afterListCommentsCounter, 1)

	mmListComments.t.Helper()

	if mmListComments.inspectFuncListComments != nil {
		mmListComments.inspectFuncListComments(ctx, filter)
	}

	mm_params := CommentUsecaseMockListCommentsParams{ctx, filter}

	// Record call args
	mmListComments.ListCommentsMock.mutex.Lock()
	mmListComments.ListCommentsMock.callArgs = append(mmListComments.ListCommentsMock.callArgs, &mm_params)
	mmListComments.ListCommentsMock.mutex.Unlock()

	for _, e := range mmListComments.ListCommentsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmListComments.ListCommentsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListComments.ListCommentsMock.defaultExpectation.Counter, 1)
		mm_want := mmListComments.ListCommentsMock.defaultExpectation.params
		mm_want_ptrs := mmListComments.ListCommentsMock.defaultExpectation.paramPtrs

		mm_got := CommentUsecaseMockListCommentsParams{ctx, filter}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListComments.t.Errorf("CommentUsecaseMock.ListComments got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListComments.ListCommentsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.filter != nil && !minimock.Equal(*mm_want_ptrs.filter, mm_got.filter) {
				mmListComments.t.Errorf("CommentUsecaseMock.ListComments got unexpected parameter filter, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListComments.ListCommentsMock.defaultExpectation.expectationOrigins.originFilter, *mm_want_ptrs.filter, mm_got.filter, minimock.Diff(*mm_want_ptrs.filter, mm_got.filter))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListComments.t.Errorf("CommentUsecaseMock.ListComments got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListComments.ListCommentsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListComments.ListCommentsMock.defaultExpectation.results
		if mm_results == nil {
			mmListComments.t.Fatal("No results are set for the CommentUsecaseMock.ListComments")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmListComments.funcListComments != nil {
		return mmListComments.funcListComments(ctx, filter)
	}
	mmListComments.t.Fatalf("Unexpected call to CommentUsecaseMock.ListComments. %v %v", ctx, filter)
	return
}

// ListCommentsAfterCounter returns a count of finished CommentUsecaseMock.ListComments invocations
func (mmListComments *CommentUsecaseMock) ListCommentsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListComments.afterListCommentsCounter)
}

// ListCommentsBeforeCounter returns a count of CommentUsecaseMock.ListComments invocations
func (mmListComments *CommentUsecaseMock) ListCommentsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListComments.beforeListCommentsCounter)
}

// Calls returns a list of arguments used in each call to CommentUsecaseMock.ListComments.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListComments *mCommentUsecaseMockListComments) Calls() []*CommentUsecaseMockListCommentsParams {
	mmListComments.mutex.RLock()

	argCopy := make([]*CommentUsecaseMockListCommentsParams, len(mmListComments.callArgs))
	copy(argCopy, mmListComments.callArgs)

	mmListComments.mutex.RUnlock()

	return argCopy
}

// MinimockListCommentsDone returns true if the count of the ListComments invocations corresponds
// the number of defined expectations
func (m *CommentUsecaseMock) MinimockListCommentsDone() bool {
	if m.ListCommentsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListCommentsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListCommentsMock.invocationsDone()
}

// MinimockListCommentsInspect logs each unmet expectation
func (m *CommentUsecaseMock) MinimockListCommentsInspect() {
	for _, e := range m.ListCommentsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentUsecaseMock.ListComments at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCommentsCounter := mm_atomic.LoadUint64(&m.afterListCommentsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListCommentsMock.defaultExpectation != nil && afterListCommentsCounter < 1 {
		if m.ListCommentsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentUsecaseMock.ListComments at\n%s", m.ListCommentsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentUsecaseMock.ListComments at\n%s with params: %#v", m.ListCommentsMock.defaultExpectation.expectationOrigins.origin, *m.ListCommentsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListComments != nil && afterListCommentsCounter < 1 {
		m.t.Errorf("Expected call to CommentUsecaseMock.ListComments at\n%s", m.funcListCommentsOrigin)
	}

	if !m.ListCommentsMock.invocationsDone() && afterListCommentsCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentUsecaseMock.ListComments at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListCommentsMock.expectedInvocations), m.ListCommentsMock.expectedInvocationsOrigin, afterListCommentsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CommentUsecaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateCommentInspect()

			m.MinimockListCommentsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CommentUsecaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CommentUsecaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateCommentDone() &&
		m.MinimockListCommentsDone()
}
