// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-graphql-service/internal/delivery/graphql.CommentConsumer -o comment_consumer_mock.go -n CommentConsumerMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-graphql-service/internal/model"
)

// CommentConsumerMock implements mm_graphql.CommentConsumer
type CommentConsumerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSubscribeToComments          func(ctx context.Context, postID int64) (ch1 <-chan model.Comment)
	funcSubscribeToCommentsOrigin    string
	inspectFuncSubscribeToComments   func(ctx context.Context, postID int64)
	afterSubscribeToCommentsCounter  uint64
	beforeSubscribeToCommentsCounter uint64
	SubscribeToCommentsMock          mCommentConsumerMockSubscribeToComments
}

// NewCommentConsumerMock returns a mock for mm_graphql.CommentConsumer
func NewCommentConsumerMock(t minimock.Tester) *CommentConsumerMock {
	m := &CommentConsumerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SubscribeToCommentsMock = mCommentConsumerMockSubscribeToComments{mock: m}
	m.SubscribeToCommentsMock.callArgs = []*CommentConsumerMockSubscribeToCommentsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCommentConsumerMockSubscribeToComments struct {
	optional           bool
	mock               *CommentConsumerMock
	defaultExpectation *CommentConsumerMockSubscribeToCommentsExpectation
	expectations       []*CommentConsumerMockSubscribeToCommentsExpectation

	callArgs []*CommentConsumerMockSubscribeToCommentsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CommentConsumerMockSubscribeToCommentsExpectation specifies expectation struct of the CommentConsumer.SubscribeToComments
type CommentConsumerMockSubscribeToCommentsExpectation struct {
	mock               *CommentConsumerMock
	params             *CommentConsumerMockSubscribeToCommentsParams
	paramPtrs          *CommentConsumerMockSubscribeToCommentsParamPtrs
	expectationOrigins CommentConsumerMockSubscribeToCommentsExpectationOrigins
	results            *CommentConsumerMockSubscribeToCommentsResults
	returnOrigin       string
	Counter            uint64
}

// CommentConsumerMockSubscribeToCommentsParams contains parameters of the CommentConsumer.SubscribeToComments
type CommentConsumerMockSubscribeToCommentsParams struct {
	ctx    context.Context
	postID int64
}

// CommentConsumerMockSubscribeToCommentsParamPtrs contains pointers to parameters of the CommentConsumer.SubscribeToComments
type CommentConsumerMockSubscribeToCommentsParamPtrs struct {
	ctx    *context.Context
	postID *int64
}

// CommentConsumerMockSubscribeToCommentsResults contains results of the CommentConsumer.SubscribeToComments
type CommentConsumerMockSubscribeToCommentsResults struct {
	ch1 <-chan model.Comment
}

// CommentConsumerMockSubscribeToCommentsOrigins contains origins of expectations of the CommentConsumer.SubscribeToComments
type CommentConsumerMockSubscribeToCommentsExpectationOrigins struct {
	origin       string
	originCtx    string
	originPostID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Optional() *mCommentConsumerMockSubscribeToComments {
	mmSubscribeToComments.optional = true
	return mmSubscribeToComments
}

// Expect sets up expected params for CommentConsumer.SubscribeToComments
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Expect(ctx context.Context, postID int64) *mCommentConsumerMockSubscribeToComments {
	if mmSubscribeToComments.mock.funcSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Set")
	}

	if mmSubscribeToComments.defaultExpectation == nil {
		mmSubscribeToComments.defaultExpectation = &CommentConsumerMockSubscribeToCommentsExpectation{}
	}

	if mmSubscribeToComments.defaultExpectation.paramPtrs != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by ExpectParams functions")
	}

	mmSubscribeToComments.defaultExpectation.params = &CommentConsumerMockSubscribeToCommentsParams{ctx, postID}
	mmSubscribeToComments.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSubscribeToComments.expectations {
		if minimock.Equal(e.params, mmSubscribeToComments.defaultExpectation.params) {
			mmSubscribeToComments.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSubscribeToComments.defaultExpectation.params)
		}
	}

	return mmSubscribeToComments
}

// ExpectCtxParam1 sets up expected param ctx for CommentConsumer.SubscribeToComments
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) ExpectCtxParam1(ctx context.Context) *mCommentConsumerMockSubscribeToComments {
	if mmSubscribeToComments.mock.funcSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Set")
	}

	if mmSubscribeToComments.defaultExpectation == nil {
		mmSubscribeToComments.defaultExpectation = &CommentConsumerMockSubscribeToCommentsExpectation{}
	}

	if mmSubscribeToComments.defaultExpectation.params != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Expect")
	}

	if mmSubscribeToComments.defaultExpectation.paramPtrs == nil {
		mmSubscribeToComments.defaultExpectation.paramPtrs = &CommentConsumerMockSubscribeToCommentsParamPtrs{}
	}
	mmSubscribeToComments.defaultExpectation.paramPtrs.ctx = &ctx
	mmSubscribeToComments.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSubscribeToComments
}

// ExpectPostIDParam2 sets up expected param postID for CommentConsumer.SubscribeToComments
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) ExpectPostIDParam2(postID int64) *mCommentConsumerMockSubscribeToComments {
	if mmSubscribeToComments.mock.funcSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Set")
	}

	if mmSubscribeToComments.defaultExpectation == nil {
		mmSubscribeToComments.defaultExpectation = &CommentConsumerMockSubscribeToCommentsExpectation{}
	}

	if mmSubscribeToComments.defaultExpectation.params != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Expect")
	}

	if mmSubscribeToComments.defaultExpectation.paramPtrs == nil {
		mmSubscribeToComments.defaultExpectation.paramPtrs = &CommentConsumerMockSubscribeToCommentsParamPtrs{}
	}
	mmSubscribeToComments.defaultExpectation.paramPtrs.postID = &postID
	mmSubscribeToComments.defaultExpectation.expectationOrigins.originPostID = minimock.CallerInfo(1)

	return mmSubscribeToComments
}

// Inspect accepts an inspector function that has same arguments as the CommentConsumer.SubscribeToComments
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Inspect(f func(ctx context.Context, postID int64)) *mCommentConsumerMockSubscribeToComments {
	if mmSubscribeToComments.mock.inspectFuncSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("Inspect function is already set for CommentConsumerMock.SubscribeToComments")
	}

	mmSubscribeToComments.mock.inspectFuncSubscribeToComments = f

	return mmSubscribeToComments
}

// Return sets up results that will be returned by CommentConsumer.SubscribeToComments
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Return(ch1 <-chan model.Comment) *CommentConsumerMock {
	if mmSubscribeToComments.mock.funcSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Set")
	}

	if mmSubscribeToComments.defaultExpectation == nil {
		mmSubscribeToComments.defaultExpectation = &CommentConsumerMockSubscribeToCommentsExpectation{mock: mmSubscribeToComments.mock}
	}
	mmSubscribeToComments.defaultExpectation.results = &CommentConsumerMockSubscribeToCommentsResults{ch1}
	mmSubscribeToComments.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSubscribeToComments.mock
}

// Set uses given function f to mock the CommentConsumer.SubscribeToComments method
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Set(f func(ctx context.Context, postID int64) (ch1 <-chan model.Comment)) *CommentConsumerMock {
	if mmSubscribeToComments.defaultExpectation != nil {
		mmSubscribeToComments.mock.t.Fatalf("Default expectation is already set for the CommentConsumer.SubscribeToComments method")
	}

	if len(mmSubscribeToComments.expectations) > 0 {
		mmSubscribeToComments.mock.t.Fatalf("Some expectations are already set for the CommentConsumer.SubscribeToComments method")
	}

	mmSubscribeToComments.mock.funcSubscribeToComments = f
	mmSubscribeToComments.mock.funcSubscribeToCommentsOrigin = minimock.CallerInfo(1)
	return mmSubscribeToComments.mock
}

// When sets expectation for the CommentConsumer.SubscribeToComments which will trigger the result defined by the following
// Then helper
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) When(ctx context.Context, postID int64) *CommentConsumerMockSubscribeToCommentsExpectation {
	if mmSubscribeToComments.mock.funcSubscribeToComments != nil {
		mmSubscribeToComments.mock.t.Fatalf("CommentConsumerMock.SubscribeToComments mock is already set by Set")
	}

	expectation := &CommentConsumerMockSubscribeToCommentsExpectation{
		mock:               mmSubscribeToComments.mock,
		params:             &CommentConsumerMockSubscribeToCommentsParams{ctx, postID},
		expectationOrigins: CommentConsumerMockSubscribeToCommentsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSubscribeToComments.expectations = append(mmSubscribeToComments.expectations, expectation)
	return expectation
}

// Then sets up CommentConsumer.SubscribeToComments return parameters for the expectation previously defined by the When method
func (e *CommentConsumerMockSubscribeToCommentsExpectation) Then(ch1 <-chan model.Comment) *CommentConsumerMock {
	e.results = &CommentConsumerMockSubscribeToCommentsResults{ch1}
	return e.mock
}

// Times sets number of times CommentConsumer.SubscribeToComments should be invoked
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Times(n uint64) *mCommentConsumerMockSubscribeToComments {
	if n == 0 {
		mmSubscribeToComments.mock.t.Fatalf("Times of CommentConsumerMock.SubscribeToComments mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSubscribeToComments.expectedInvocations, n)
	mmSubscribeToComments.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSubscribeToComments
}

func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) invocationsDone() bool {
	if len(mmSubscribeToComments.expectations) == 0 && mmSubscribeToComments.defaultExpectation == nil && mmSubscribeToComments.mock.funcSubscribeToComments == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSubscribeToComments.mock.afterSubscribeToCommentsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSubscribeToComments.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SubscribeToComments implements mm_graphql.CommentConsumer
func (mmSubscribeToComments *CommentConsumerMock) SubscribeToComments(ctx context.Context, postID int64) (ch1 <-chan model.Comment) {
	mm_atomic.AddUint64(&mmSubscribeToComments.beforeSubscribeToCommentsCounter, 1)
	defer mm_atomic.AddUint64(&mmSubscribeToComments.afterSubscribeToCommentsCounter, 1)

	mmSubscribeToComments.t.Helper()

	if mmSubscribeToComments.inspectFuncSubscribeToComments != nil {
		mmSubscribeToComments.inspectFuncSubscribeToComments(ctx, postID)
	}

	mm_params := CommentConsumerMockSubscribeToCommentsParams{ctx, postID}

	// Record call args
	mmSubscribeToComments.SubscribeToCommentsMock.mutex.Lock()
	mmSubscribeToComments.SubscribeToCommentsMock.callArgs = append(mmSubscribeToComments.SubscribeToCommentsMock.callArgs, &mm_params)
	mmSubscribeToComments.SubscribeToCommentsMock.mutex.Unlock()

	for _, e := range mmSubscribeToComments.SubscribeToCommentsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ch1
		}
	}

	if mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.Counter, 1)
		mm_want := mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.params
		mm_want_ptrs := mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.paramPtrs

		mm_got := CommentConsumerMockSubscribeToCommentsParams{ctx, postID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSubscribeToComments.t.Errorf("CommentConsumerMock.SubscribeToComments got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.postID != nil && !minimock.Equal(*mm_want_ptrs.postID, mm_got.postID) {
				mmSubscribeToComments.t.Errorf("CommentConsumerMock.SubscribeToComments got unexpected parameter postID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.expectationOrigins.originPostID, *mm_want_ptrs.postID, mm_got.postID, minimock.Diff(*mm_want_ptrs.postID, mm_got.postID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSubscribeToComments.t.Errorf("CommentConsumerMock.SubscribeToComments got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSubscribeToComments.SubscribeToCommentsMock.defaultExpectation.results
		if mm_results == nil {
			mmSubscribeToComments.t.Fatal("No results are set for the CommentConsumerMock.SubscribeToComments")
		}
		return (*mm_results).ch1
	}
	if mmSubscribeToComments.funcSubscribeToComments != nil {
		return mmSubscribeToComments.funcSubscribeToComments(ctx, postID)
	}
	mmSubscribeToComments.t.Fatalf("Unexpected call to CommentConsumerMock.SubscribeToComments. %v %v", ctx, postID)
	return
}

// SubscribeToCommentsAfterCounter returns a count of finished CommentConsumerMock.SubscribeToComments invocations
func (mmSubscribeToComments *CommentConsumerMock) SubscribeToCommentsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubscribeToComments.afterSubscribeToCommentsCounter)
}

// SubscribeToCommentsBeforeCounter returns a count of CommentConsumerMock.SubscribeToComments invocations
func (mmSubscribeToComments *CommentConsumerMock) SubscribeToCommentsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubscribeToComments.beforeSubscribeToCommentsCounter)
}

// Calls returns a list of arguments used in each call to CommentConsumerMock.SubscribeToComments.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSubscribeToComments *mCommentConsumerMockSubscribeToComments) Calls() []*CommentConsumerMockSubscribeToCommentsParams {
	mmSubscribeToComments.mutex.RLock()

	argCopy := make([]*CommentConsumerMockSubscribeToCommentsParams, len(mmSubscribeToComments.callArgs))
	copy(argCopy, mmSubscribeToComments.callArgs)

	mmSubscribeToComments.mutex.RUnlock()

	return argCopy
}

// MinimockSubscribeToCommentsDone returns true if the count of the SubscribeToComments invocations corresponds
// the number of defined expectations
func (m *CommentConsumerMock) MinimockSubscribeToCommentsDone() bool {
	if m.SubscribeToCommentsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SubscribeToCommentsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SubscribeToCommentsMock.invocationsDone()
}

// MinimockSubscribeToCommentsInspect logs each unmet expectation
func (m *CommentConsumerMock) MinimockSubscribeToCommentsInspect() {
	for _, e := range m.SubscribeToCommentsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CommentConsumerMock.SubscribeToComments at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSubscribeToCommentsCounter := mm_atomic.LoadUint64(&m.afterSubscribeToCommentsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SubscribeToCommentsMock.defaultExpectation != nil && afterSubscribeToCommentsCounter < 1 {
		if m.SubscribeToCommentsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CommentConsumerMock.SubscribeToComments at\n%s", m.SubscribeToCommentsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CommentConsumerMock.SubscribeToComments at\n%s with params: %#v", m.SubscribeToCommentsMock.defaultExpectation.expectationOrigins.origin, *m.SubscribeToCommentsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubscribeToComments != nil && afterSubscribeToCommentsCounter < 1 {
		m.t.Errorf("Expected call to CommentConsumerMock.SubscribeToComments at\n%s", m.funcSubscribeToCommentsOrigin)
	}

	if !m.SubscribeToCommentsMock.invocationsDone() && afterSubscribeToCommentsCounter > 0 {
		m.t.Errorf("Expected %d calls to CommentConsumerMock.SubscribeToComments at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SubscribeToCommentsMock.expectedInvocations), m.SubscribeToCommentsMock.expectedInvocationsOrigin, afterSubscribeToCommentsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CommentConsumerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSubscribeToCommentsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CommentConsumerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CommentConsumerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSubscribeToCommentsDone()
}
