// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mock

//go:generate minimock -i github.com/solumD/ozon-grapql-service/internal/delivery/graphql.PostUsecase -o post_usecase_mock.go -n PostUsecaseMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/solumD/ozon-grapql-service/internal/model"
)

// PostUsecaseMock implements mm_graphql.PostUsecase
type PostUsecaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcChangeCommentsAvailability          func(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error)
	funcChangeCommentsAvailabilityOrigin    string
	inspectFuncChangeCommentsAvailability   func(ctx context.Context, postID int64, enabled bool)
	afterChangeCommentsAvailabilityCounter  uint64
	beforeChangeCommentsAvailabilityCounter uint64
	ChangeCommentsAvailabilityMock          mPostUsecaseMockChangeCommentsAvailability

	funcCreatePost          func(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) (p1 model.Post, err error)
	funcCreatePostOrigin    string
	inspectFuncCreatePost   func(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool)
	afterCreatePostCounter  uint64
	beforeCreatePostCounter uint64
	CreatePostMock          mPostUsecaseMockCreatePost

	funcGetPost          func(ctx context.Context, id int64) (p1 model.Post, err error)
	funcGetPostOrigin    string
	inspectFuncGetPost   func(ctx context.Context, id int64)
	afterGetPostCounter  uint64
	beforeGetPostCounter uint64
	GetPostMock          mPostUsecaseMockGetPost

	funcListPosts          func(ctx context.Context) (pa1 []model.Post, err error)
	funcListPostsOrigin    string
	inspectFuncListPosts   func(ctx context.Context)
	afterListPostsCounter  uint64
	beforeListPostsCounter uint64
	ListPostsMock          mPostUsecaseMockListPosts
}

// NewPostUsecaseMock returns a mock for mm_graphql.PostUsecase
func NewPostUsecaseMock(t minimock.Tester) *PostUsecaseMock {
	m := &PostUsecaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ChangeCommentsAvailabilityMock = mPostUsecaseMockChangeCommentsAvailability{mock: m}
	m.ChangeCommentsAvailabilityMock.callArgs = []*PostUsecaseMockChangeCommentsAvailabilityParams{}

	m.CreatePostMock = mPostUsecaseMockCreatePost{mock: m}
	m.CreatePostMock.callArgs = []*PostUsecaseMockCreatePostParams{}

	m.GetPostMock = mPostUsecaseMockGetPost{mock: m}
	m.GetPostMock.callArgs = []*PostUsecaseMockGetPostParams{}

	m.ListPostsMock = mPostUsecaseMockListPosts{mock: m}
	m.ListPostsMock.callArgs = []*PostUsecaseMockListPostsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPostUsecaseMockChangeCommentsAvailability struct {
	optional           bool
	mock               *PostUsecaseMock
	defaultExpectation *PostUsecaseMockChangeCommentsAvailabilityExpectation
	expectations       []*PostUsecaseMockChangeCommentsAvailabilityExpectation

	callArgs []*PostUsecaseMockChangeCommentsAvailabilityParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostUsecaseMockChangeCommentsAvailabilityExpectation specifies expectation struct of the PostUsecase.ChangeCommentsAvailability
type PostUsecaseMockChangeCommentsAvailabilityExpectation struct {
	mock               *PostUsecaseMock
	params             *PostUsecaseMockChangeCommentsAvailabilityParams
	paramPtrs          *PostUsecaseMockChangeCommentsAvailabilityParamPtrs
	expectationOrigins PostUsecaseMockChangeCommentsAvailabilityExpectationOrigins
	results            *PostUsecaseMockChangeCommentsAvailabilityResults
	returnOrigin       string
	Counter            uint64
}

// PostUsecaseMockChangeCommentsAvailabilityParams contains parameters of the PostUsecase.ChangeCommentsAvailability
type PostUsecaseMockChangeCommentsAvailabilityParams struct {
	ctx     context.Context
	postID  int64
	enabled bool
}

// PostUsecaseMockChangeCommentsAvailabilityParamPtrs contains pointers to parameters of the PostUsecase.ChangeCommentsAvailability
type PostUsecaseMockChangeCommentsAvailabilityParamPtrs struct {
	ctx     *context.Context
	postID  *int64
	enabled *bool
}

// PostUsecaseMockChangeCommentsAvailabilityResults contains results of the PostUsecase.ChangeCommentsAvailability
type PostUsecaseMockChangeCommentsAvailabilityResults struct {
	p1  model.Post
	err error
}

// PostUsecaseMockChangeCommentsAvailabilityOrigins contains origins of expectations of the PostUsecase.ChangeCommentsAvailability
type PostUsecaseMockChangeCommentsAvailabilityExpectationOrigins struct {
	origin        string
	originCtx     string
	originPostID  string
	originEnabled string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Optional() *mPostUsecaseMockChangeCommentsAvailability {
	mmChangeCommentsAvailability.optional = true
	return mmChangeCommentsAvailability
}

// Expect sets up expected params for PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Expect(ctx context.Context, postID int64, enabled bool) *mPostUsecaseMockChangeCommentsAvailability {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	if mmChangeCommentsAvailability.defaultExpectation == nil {
		mmChangeCommentsAvailability.defaultExpectation = &PostUsecaseMockChangeCommentsAvailabilityExpectation{}
	}

	if mmChangeCommentsAvailability.defaultExpectation.paramPtrs != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by ExpectParams functions")
	}

	mmChangeCommentsAvailability.defaultExpectation.params = &PostUsecaseMockChangeCommentsAvailabilityParams{ctx, postID, enabled}
	mmChangeCommentsAvailability.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmChangeCommentsAvailability.expectations {
		if minimock.Equal(e.params, mmChangeCommentsAvailability.defaultExpectation.params) {
			mmChangeCommentsAvailability.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmChangeCommentsAvailability.defaultExpectation.params)
		}
	}

	return mmChangeCommentsAvailability
}

// ExpectCtxParam1 sets up expected param ctx for PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) ExpectCtxParam1(ctx context.Context) *mPostUsecaseMockChangeCommentsAvailability {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	if mmChangeCommentsAvailability.defaultExpectation == nil {
		mmChangeCommentsAvailability.defaultExpectation = &PostUsecaseMockChangeCommentsAvailabilityExpectation{}
	}

	if mmChangeCommentsAvailability.defaultExpectation.params != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Expect")
	}

	if mmChangeCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmChangeCommentsAvailability.defaultExpectation.paramPtrs = &PostUsecaseMockChangeCommentsAvailabilityParamPtrs{}
	}
	mmChangeCommentsAvailability.defaultExpectation.paramPtrs.ctx = &ctx
	mmChangeCommentsAvailability.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmChangeCommentsAvailability
}

// ExpectPostIDParam2 sets up expected param postID for PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) ExpectPostIDParam2(postID int64) *mPostUsecaseMockChangeCommentsAvailability {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	if mmChangeCommentsAvailability.defaultExpectation == nil {
		mmChangeCommentsAvailability.defaultExpectation = &PostUsecaseMockChangeCommentsAvailabilityExpectation{}
	}

	if mmChangeCommentsAvailability.defaultExpectation.params != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Expect")
	}

	if mmChangeCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmChangeCommentsAvailability.defaultExpectation.paramPtrs = &PostUsecaseMockChangeCommentsAvailabilityParamPtrs{}
	}
	mmChangeCommentsAvailability.defaultExpectation.paramPtrs.postID = &postID
	mmChangeCommentsAvailability.defaultExpectation.expectationOrigins.originPostID = minimock.CallerInfo(1)

	return mmChangeCommentsAvailability
}

// ExpectEnabledParam3 sets up expected param enabled for PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) ExpectEnabledParam3(enabled bool) *mPostUsecaseMockChangeCommentsAvailability {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	if mmChangeCommentsAvailability.defaultExpectation == nil {
		mmChangeCommentsAvailability.defaultExpectation = &PostUsecaseMockChangeCommentsAvailabilityExpectation{}
	}

	if mmChangeCommentsAvailability.defaultExpectation.params != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Expect")
	}

	if mmChangeCommentsAvailability.defaultExpectation.paramPtrs == nil {
		mmChangeCommentsAvailability.defaultExpectation.paramPtrs = &PostUsecaseMockChangeCommentsAvailabilityParamPtrs{}
	}
	mmChangeCommentsAvailability.defaultExpectation.paramPtrs.enabled = &enabled
	mmChangeCommentsAvailability.defaultExpectation.expectationOrigins.originEnabled = minimock.CallerInfo(1)

	return mmChangeCommentsAvailability
}

// Inspect accepts an inspector function that has same arguments as the PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Inspect(f func(ctx context.Context, postID int64, enabled bool)) *mPostUsecaseMockChangeCommentsAvailability {
	if mmChangeCommentsAvailability.mock.inspectFuncChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("Inspect function is already set for PostUsecaseMock.ChangeCommentsAvailability")
	}

	mmChangeCommentsAvailability.mock.inspectFuncChangeCommentsAvailability = f

	return mmChangeCommentsAvailability
}

// Return sets up results that will be returned by PostUsecase.ChangeCommentsAvailability
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Return(p1 model.Post, err error) *PostUsecaseMock {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	if mmChangeCommentsAvailability.defaultExpectation == nil {
		mmChangeCommentsAvailability.defaultExpectation = &PostUsecaseMockChangeCommentsAvailabilityExpectation{mock: mmChangeCommentsAvailability.mock}
	}
	mmChangeCommentsAvailability.defaultExpectation.results = &PostUsecaseMockChangeCommentsAvailabilityResults{p1, err}
	mmChangeCommentsAvailability.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmChangeCommentsAvailability.mock
}

// Set uses given function f to mock the PostUsecase.ChangeCommentsAvailability method
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Set(f func(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error)) *PostUsecaseMock {
	if mmChangeCommentsAvailability.defaultExpectation != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("Default expectation is already set for the PostUsecase.ChangeCommentsAvailability method")
	}

	if len(mmChangeCommentsAvailability.expectations) > 0 {
		mmChangeCommentsAvailability.mock.t.Fatalf("Some expectations are already set for the PostUsecase.ChangeCommentsAvailability method")
	}

	mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability = f
	mmChangeCommentsAvailability.mock.funcChangeCommentsAvailabilityOrigin = minimock.CallerInfo(1)
	return mmChangeCommentsAvailability.mock
}

// When sets expectation for the PostUsecase.ChangeCommentsAvailability which will trigger the result defined by the following
// Then helper
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) When(ctx context.Context, postID int64, enabled bool) *PostUsecaseMockChangeCommentsAvailabilityExpectation {
	if mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.mock.t.Fatalf("PostUsecaseMock.ChangeCommentsAvailability mock is already set by Set")
	}

	expectation := &PostUsecaseMockChangeCommentsAvailabilityExpectation{
		mock:               mmChangeCommentsAvailability.mock,
		params:             &PostUsecaseMockChangeCommentsAvailabilityParams{ctx, postID, enabled},
		expectationOrigins: PostUsecaseMockChangeCommentsAvailabilityExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmChangeCommentsAvailability.expectations = append(mmChangeCommentsAvailability.expectations, expectation)
	return expectation
}

// Then sets up PostUsecase.ChangeCommentsAvailability return parameters for the expectation previously defined by the When method
func (e *PostUsecaseMockChangeCommentsAvailabilityExpectation) Then(p1 model.Post, err error) *PostUsecaseMock {
	e.results = &PostUsecaseMockChangeCommentsAvailabilityResults{p1, err}
	return e.mock
}

// Times sets number of times PostUsecase.ChangeCommentsAvailability should be invoked
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Times(n uint64) *mPostUsecaseMockChangeCommentsAvailability {
	if n == 0 {
		mmChangeCommentsAvailability.mock.t.Fatalf("Times of PostUsecaseMock.ChangeCommentsAvailability mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmChangeCommentsAvailability.expectedInvocations, n)
	mmChangeCommentsAvailability.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmChangeCommentsAvailability
}

func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) invocationsDone() bool {
	if len(mmChangeCommentsAvailability.expectations) == 0 && mmChangeCommentsAvailability.defaultExpectation == nil && mmChangeCommentsAvailability.mock.funcChangeCommentsAvailability == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmChangeCommentsAvailability.mock.afterChangeCommentsAvailabilityCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmChangeCommentsAvailability.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ChangeCommentsAvailability implements mm_graphql.PostUsecase
func (mmChangeCommentsAvailability *PostUsecaseMock) ChangeCommentsAvailability(ctx context.Context, postID int64, enabled bool) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmChangeCommentsAvailability.beforeChangeCommentsAvailabilityCounter, 1)
	defer mm_atomic.AddUint64(&mmChangeCommentsAvailability.afterChangeCommentsAvailabilityCounter, 1)

	mmChangeCommentsAvailability.t.Helper()

	if mmChangeCommentsAvailability.inspectFuncChangeCommentsAvailability != nil {
		mmChangeCommentsAvailability.inspectFuncChangeCommentsAvailability(ctx, postID, enabled)
	}

	mm_params := PostUsecaseMockChangeCommentsAvailabilityParams{ctx, postID, enabled}

	// Record call args
	mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.mutex.Lock()
	mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.callArgs = append(mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.callArgs, &mm_params)
	mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.mutex.Unlock()

	for _, e := range mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.Counter, 1)
		mm_want := mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.params
		mm_want_ptrs := mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.paramPtrs

		mm_got := PostUsecaseMockChangeCommentsAvailabilityParams{ctx, postID, enabled}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmChangeCommentsAvailability.t.Errorf("PostUsecaseMock.ChangeCommentsAvailability got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.postID != nil && !minimock.Equal(*mm_want_ptrs.postID, mm_got.postID) {
				mmChangeCommentsAvailability.t.Errorf("PostUsecaseMock.ChangeCommentsAvailability got unexpected parameter postID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originPostID, *mm_want_ptrs.postID, mm_got.postID, minimock.Diff(*mm_want_ptrs.postID, mm_got.postID))
			}

			if mm_want_ptrs.enabled != nil && !minimock.Equal(*mm_want_ptrs.enabled, mm_got.enabled) {
				mmChangeCommentsAvailability.t.Errorf("PostUsecaseMock.ChangeCommentsAvailability got unexpected parameter enabled, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.expectationOrigins.originEnabled, *mm_want_ptrs.enabled, mm_got.enabled, minimock.Diff(*mm_want_ptrs.enabled, mm_got.enabled))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmChangeCommentsAvailability.t.Errorf("PostUsecaseMock.ChangeCommentsAvailability got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmChangeCommentsAvailability.ChangeCommentsAvailabilityMock.defaultExpectation.results
		if mm_results == nil {
			mmChangeCommentsAvailability.t.Fatal("No results are set for the PostUsecaseMock.ChangeCommentsAvailability")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmChangeCommentsAvailability.funcChangeCommentsAvailability != nil {
		return mmChangeCommentsAvailability.funcChangeCommentsAvailability(ctx, postID, enabled)
	}
	mmChangeCommentsAvailability.t.Fatalf("Unexpected call to PostUsecaseMock.ChangeCommentsAvailability. %v %v %v", ctx, postID, enabled)
	return
}

// ChangeCommentsAvailabilityAfterCounter returns a count of finished PostUsecaseMock.ChangeCommentsAvailability invocations
func (mmChangeCommentsAvailability *PostUsecaseMock) ChangeCommentsAvailabilityAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmChangeCommentsAvailability.afterChangeCommentsAvailabilityCounter)
}

// ChangeCommentsAvailabilityBeforeCounter returns a count of PostUsecaseMock.ChangeCommentsAvailability invocations
func (mmChangeCommentsAvailability *PostUsecaseMock) ChangeCommentsAvailabilityBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmChangeCommentsAvailability.beforeChangeCommentsAvailabilityCounter)
}

// Calls returns a list of arguments used in each call to PostUsecaseMock.ChangeCommentsAvailability.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmChangeCommentsAvailability *mPostUsecaseMockChangeCommentsAvailability) Calls() []*PostUsecaseMockChangeCommentsAvailabilityParams {
	mmChangeCommentsAvailability.mutex.RLock()

	argCopy := make([]*PostUsecaseMockChangeCommentsAvailabilityParams, len(mmChangeCommentsAvailability.callArgs))
	copy(argCopy, mmChangeCommentsAvailability.callArgs)

	mmChangeCommentsAvailability.mutex.RUnlock()

	return argCopy
}

// MinimockChangeCommentsAvailabilityDone returns true if the count of the ChangeCommentsAvailability invocations corresponds
// the number of defined expectations
func (m *PostUsecaseMock) MinimockChangeCommentsAvailabilityDone() bool {
	if m.ChangeCommentsAvailabilityMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ChangeCommentsAvailabilityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ChangeCommentsAvailabilityMock.invocationsDone()
}

// MinimockChangeCommentsAvailabilityInspect logs each unmet expectation
func (m *PostUsecaseMock) MinimockChangeCommentsAvailabilityInspect() {
	for _, e := range m.ChangeCommentsAvailabilityMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostUsecaseMock.ChangeCommentsAvailability at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterChangeCommentsAvailabilityCounter := mm_atomic.LoadUint64(&m.afterChangeCommentsAvailabilityCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ChangeCommentsAvailabilityMock.defaultExpectation != nil && afterChangeCommentsAvailabilityCounter < 1 {
		if m.ChangeCommentsAvailabilityMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostUsecaseMock.ChangeCommentsAvailability at\n%s", m.ChangeCommentsAvailabilityMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostUsecaseMock.ChangeCommentsAvailability at\n%s with params: %#v", m.ChangeCommentsAvailabilityMock.defaultExpectation.expectationOrigins.origin, *m.ChangeCommentsAvailabilityMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcChangeCommentsAvailability != nil && afterChangeCommentsAvailabilityCounter < 1 {
		m.t.Errorf("Expected call to PostUsecaseMock.ChangeCommentsAvailability at\n%s", m.funcChangeCommentsAvailabilityOrigin)
	}

	if !m.ChangeCommentsAvailabilityMock.invocationsDone() && afterChangeCommentsAvailabilityCounter > 0 {
		m.t.Errorf("Expected %d calls to PostUsecaseMock.ChangeCommentsAvailability at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ChangeCommentsAvailabilityMock.expectedInvocations), m.ChangeCommentsAvailabilityMock.expectedInvocationsOrigin, afterChangeCommentsAvailabilityCounter)
	}
}

type mPostUsecaseMockCreatePost struct {
	optional           bool
	mock               *PostUsecaseMock
	defaultExpectation *PostUsecaseMockCreatePostExpectation
	expectations       []*PostUsecaseMockCreatePostExpectation

	callArgs []*PostUsecaseMockCreatePostParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostUsecaseMockCreatePostExpectation specifies expectation struct of the PostUsecase.CreatePost
type PostUsecaseMockCreatePostExpectation struct {
	mock               *PostUsecaseMock
	params             *PostUsecaseMockCreatePostParams
	paramPtrs          *PostUsecaseMockCreatePostParamPtrs
	expectationOrigins PostUsecaseMockCreatePostExpectationOrigins
	results            *PostUsecaseMockCreatePostResults
	returnOrigin       string
	Counter            uint64
}

// PostUsecaseMockCreatePostParams contains parameters of the PostUsecase.CreatePost
type PostUsecaseMockCreatePostParams struct {
	ctx             context.Context
	userUUID        string
	title           string
	content         string
	commentsEnabled bool
}

// PostUsecaseMockCreatePostParamPtrs contains pointers to parameters of the PostUsecase.CreatePost
type PostUsecaseMockCreatePostParamPtrs struct {
	ctx             *context.Context
	userUUID        *string
	title           *string
	content         *string
	commentsEnabled *bool
}

// PostUsecaseMockCreatePostResults contains results of the PostUsecase.CreatePost
type PostUsecaseMockCreatePostResults struct {
	p1  model.Post
	err error
}

// PostUsecaseMockCreatePostOrigins contains origins of expectations of the PostUsecase.CreatePost
type PostUsecaseMockCreatePostExpectationOrigins struct {
	origin                string
	originCtx             string
	originUserUUID        string
	originTitle           string
	originContent         string
	originCommentsEnabled string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreatePost *mPostUsecaseMockCreatePost) Optional() *mPostUsecaseMockCreatePost {
	mmCreatePost.optional = true
	return mmCreatePost
}

// Expect sets up expected params for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) Expect(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.paramPtrs != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by ExpectParams functions")
	}

	mmCreatePost.defaultExpectation.params = &PostUsecaseMockCreatePostParams{ctx, userUUID, title, content, commentsEnabled}
	mmCreatePost.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreatePost.expectations {
		if minimock.Equal(e.params, mmCreatePost.defaultExpectation.params) {
			mmCreatePost.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreatePost.defaultExpectation.params)
		}
	}

	return mmCreatePost
}

// ExpectCtxParam1 sets up expected param ctx for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) ExpectCtxParam1(ctx context.Context) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.params != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Expect")
	}

	if mmCreatePost.defaultExpectation.paramPtrs == nil {
		mmCreatePost.defaultExpectation.paramPtrs = &PostUsecaseMockCreatePostParamPtrs{}
	}
	mmCreatePost.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreatePost.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreatePost
}

// ExpectUserUUIDParam2 sets up expected param userUUID for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) ExpectUserUUIDParam2(userUUID string) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.params != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Expect")
	}

	if mmCreatePost.defaultExpectation.paramPtrs == nil {
		mmCreatePost.defaultExpectation.paramPtrs = &PostUsecaseMockCreatePostParamPtrs{}
	}
	mmCreatePost.defaultExpectation.paramPtrs.userUUID = &userUUID
	mmCreatePost.defaultExpectation.expectationOrigins.originUserUUID = minimock.CallerInfo(1)

	return mmCreatePost
}

// ExpectTitleParam3 sets up expected param title for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) ExpectTitleParam3(title string) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.params != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Expect")
	}

	if mmCreatePost.defaultExpectation.paramPtrs == nil {
		mmCreatePost.defaultExpectation.paramPtrs = &PostUsecaseMockCreatePostParamPtrs{}
	}
	mmCreatePost.defaultExpectation.paramPtrs.title = &title
	mmCreatePost.defaultExpectation.expectationOrigins.originTitle = minimock.CallerInfo(1)

	return mmCreatePost
}

// ExpectContentParam4 sets up expected param content for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) ExpectContentParam4(content string) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.params != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Expect")
	}

	if mmCreatePost.defaultExpectation.paramPtrs == nil {
		mmCreatePost.defaultExpectation.paramPtrs = &PostUsecaseMockCreatePostParamPtrs{}
	}
	mmCreatePost.defaultExpectation.paramPtrs.content = &content
	mmCreatePost.defaultExpectation.expectationOrigins.originContent = minimock.CallerInfo(1)

	return mmCreatePost
}

// ExpectCommentsEnabledParam5 sets up expected param commentsEnabled for PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) ExpectCommentsEnabledParam5(commentsEnabled bool) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{}
	}

	if mmCreatePost.defaultExpectation.params != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Expect")
	}

	if mmCreatePost.defaultExpectation.paramPtrs == nil {
		mmCreatePost.defaultExpectation.paramPtrs = &PostUsecaseMockCreatePostParamPtrs{}
	}
	mmCreatePost.defaultExpectation.paramPtrs.commentsEnabled = &commentsEnabled
	mmCreatePost.defaultExpectation.expectationOrigins.originCommentsEnabled = minimock.CallerInfo(1)

	return mmCreatePost
}

// Inspect accepts an inspector function that has same arguments as the PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) Inspect(f func(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool)) *mPostUsecaseMockCreatePost {
	if mmCreatePost.mock.inspectFuncCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("Inspect function is already set for PostUsecaseMock.CreatePost")
	}

	mmCreatePost.mock.inspectFuncCreatePost = f

	return mmCreatePost
}

// Return sets up results that will be returned by PostUsecase.CreatePost
func (mmCreatePost *mPostUsecaseMockCreatePost) Return(p1 model.Post, err error) *PostUsecaseMock {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	if mmCreatePost.defaultExpectation == nil {
		mmCreatePost.defaultExpectation = &PostUsecaseMockCreatePostExpectation{mock: mmCreatePost.mock}
	}
	mmCreatePost.defaultExpectation.results = &PostUsecaseMockCreatePostResults{p1, err}
	mmCreatePost.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreatePost.mock
}

// Set uses given function f to mock the PostUsecase.CreatePost method
func (mmCreatePost *mPostUsecaseMockCreatePost) Set(f func(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) (p1 model.Post, err error)) *PostUsecaseMock {
	if mmCreatePost.defaultExpectation != nil {
		mmCreatePost.mock.t.Fatalf("Default expectation is already set for the PostUsecase.CreatePost method")
	}

	if len(mmCreatePost.expectations) > 0 {
		mmCreatePost.mock.t.Fatalf("Some expectations are already set for the PostUsecase.CreatePost method")
	}

	mmCreatePost.mock.funcCreatePost = f
	mmCreatePost.mock.funcCreatePostOrigin = minimock.CallerInfo(1)
	return mmCreatePost.mock
}

// When sets expectation for the PostUsecase.CreatePost which will trigger the result defined by the following
// Then helper
func (mmCreatePost *mPostUsecaseMockCreatePost) When(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) *PostUsecaseMockCreatePostExpectation {
	if mmCreatePost.mock.funcCreatePost != nil {
		mmCreatePost.mock.t.Fatalf("PostUsecaseMock.CreatePost mock is already set by Set")
	}

	expectation := &PostUsecaseMockCreatePostExpectation{
		mock:               mmCreatePost.mock,
		params:             &PostUsecaseMockCreatePostParams{ctx, userUUID, title, content, commentsEnabled},
		expectationOrigins: PostUsecaseMockCreatePostExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreatePost.expectations = append(mmCreatePost.expectations, expectation)
	return expectation
}

// Then sets up PostUsecase.CreatePost return parameters for the expectation previously defined by the When method
func (e *PostUsecaseMockCreatePostExpectation) Then(p1 model.Post, err error) *PostUsecaseMock {
	e.results = &PostUsecaseMockCreatePostResults{p1, err}
	return e.mock
}

// Times sets number of times PostUsecase.CreatePost should be invoked
func (mmCreatePost *mPostUsecaseMockCreatePost) Times(n uint64) *mPostUsecaseMockCreatePost {
	if n == 0 {
		mmCreatePost.mock.t.Fatalf("Times of PostUsecaseMock.CreatePost mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreatePost.expectedInvocations, n)
	mmCreatePost.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreatePost
}

func (mmCreatePost *mPostUsecaseMockCreatePost) invocationsDone() bool {
	if len(mmCreatePost.expectations) == 0 && mmCreatePost.defaultExpectation == nil && mmCreatePost.mock.funcCreatePost == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreatePost.mock.afterCreatePostCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreatePost.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreatePost implements mm_graphql.PostUsecase
func (mmCreatePost *PostUsecaseMock) CreatePost(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmCreatePost.beforeCreatePostCounter, 1)
	defer mm_atomic.AddUint64(&mmCreatePost.afterCreatePostCounter, 1)

	mmCreatePost.t.Helper()

	if mmCreatePost.inspectFuncCreatePost != nil {
		mmCreatePost.inspectFuncCreatePost(ctx, userUUID, title, content, commentsEnabled)
	}

	mm_params := PostUsecaseMockCreatePostParams{ctx, userUUID, title, content, commentsEnabled}

	// Record call args
	mmCreatePost.CreatePostMock.mutex.Lock()
	mmCreatePost.CreatePostMock.callArgs = append(mmCreatePost.CreatePostMock.callArgs, &mm_params)
	mmCreatePost.CreatePostMock.mutex.Unlock()

	for _, e := range mmCreatePost.CreatePostMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmCreatePost.CreatePostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreatePost.CreatePostMock.defaultExpectation.Counter, 1)
		mm_want := mmCreatePost.CreatePostMock.defaultExpectation.params
		mm_want_ptrs := mmCreatePost.CreatePostMock.defaultExpectation.paramPtrs

		mm_got := PostUsecaseMockCreatePostParams{ctx, userUUID, title, content, commentsEnabled}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userUUID != nil && !minimock.Equal(*mm_want_ptrs.userUUID, mm_got.userUUID) {
				mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameter userUUID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.originUserUUID, *mm_want_ptrs.userUUID, mm_got.userUUID, minimock.Diff(*mm_want_ptrs.userUUID, mm_got.userUUID))
			}

			if mm_want_ptrs.title != nil && !minimock.Equal(*mm_want_ptrs.title, mm_got.title) {
				mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameter title, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.originTitle, *mm_want_ptrs.title, mm_got.title, minimock.Diff(*mm_want_ptrs.title, mm_got.title))
			}

			if mm_want_ptrs.content != nil && !minimock.Equal(*mm_want_ptrs.content, mm_got.content) {
				mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameter content, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.originContent, *mm_want_ptrs.content, mm_got.content, minimock.Diff(*mm_want_ptrs.content, mm_got.content))
			}

			if mm_want_ptrs.commentsEnabled != nil && !minimock.Equal(*mm_want_ptrs.commentsEnabled, mm_got.commentsEnabled) {
				mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameter commentsEnabled, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.originCommentsEnabled, *mm_want_ptrs.commentsEnabled, mm_got.commentsEnabled, minimock.Diff(*mm_want_ptrs.commentsEnabled, mm_got.commentsEnabled))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreatePost.t.Errorf("PostUsecaseMock.CreatePost got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreatePost.CreatePostMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreatePost.CreatePostMock.defaultExpectation.results
		if mm_results == nil {
			mmCreatePost.t.Fatal("No results are set for the PostUsecaseMock.CreatePost")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmCreatePost.funcCreatePost != nil {
		return mmCreatePost.funcCreatePost(ctx, userUUID, title, content, commentsEnabled)
	}
	mmCreatePost.t.Fatalf("Unexpected call to PostUsecaseMock.CreatePost. %v %v %v %v %v", ctx, userUUID, title, content, commentsEnabled)
	return
}

// CreatePostAfterCounter returns a count of finished PostUsecaseMock.CreatePost invocations
func (mmCreatePost *PostUsecaseMock) CreatePostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePost.afterCreatePostCounter)
}

// CreatePostBeforeCounter returns a count of PostUsecaseMock.CreatePost invocations
func (mmCreatePost *PostUsecaseMock) CreatePostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePost.beforeCreatePostCounter)
}

// Calls returns a list of arguments used in each call to PostUsecaseMock.CreatePost.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreatePost *mPostUsecaseMockCreatePost) Calls() []*PostUsecaseMockCreatePostParams {
	mmCreatePost.mutex.RLock()

	argCopy := make([]*PostUsecaseMockCreatePostParams, len(mmCreatePost.callArgs))
	copy(argCopy, mmCreatePost.callArgs)

	mmCreatePost.mutex.RUnlock()

	return argCopy
}

// MinimockCreatePostDone returns true if the count of the CreatePost invocations corresponds
// the number of defined expectations
func (m *PostUsecaseMock) MinimockCreatePostDone() bool {
	if m.CreatePostMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreatePostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreatePostMock.invocationsDone()
}

// MinimockCreatePostInspect logs each unmet expectation
func (m *PostUsecaseMock) MinimockCreatePostInspect() {
	for _, e := range m.CreatePostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostUsecaseMock.CreatePost at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreatePostCounter := mm_atomic.LoadUint64(&m.afterCreatePostCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreatePostMock.defaultExpectation != nil && afterCreatePostCounter < 1 {
		if m.CreatePostMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostUsecaseMock.CreatePost at\n%s", m.CreatePostMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostUsecaseMock.CreatePost at\n%s with params: %#v", m.CreatePostMock.defaultExpectation.expectationOrigins.origin, *m.CreatePostMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreatePost != nil && afterCreatePostCounter < 1 {
		m.t.Errorf("Expected call to PostUsecaseMock.CreatePost at\n%s", m.funcCreatePostOrigin)
	}

	if !m.CreatePostMock.invocationsDone() && afterCreatePostCounter > 0 {
		m.t.Errorf("Expected %d calls to PostUsecaseMock.CreatePost at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreatePostMock.expectedInvocations), m.CreatePostMock.expectedInvocationsOrigin, afterCreatePostCounter)
	}
}

type mPostUsecaseMockGetPost struct {
	optional           bool
	mock               *PostUsecaseMock
	defaultExpectation *PostUsecaseMockGetPostExpectation
	expectations       []*PostUsecaseMockGetPostExpectation

	callArgs []*PostUsecaseMockGetPostParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostUsecaseMockGetPostExpectation specifies expectation struct of the PostUsecase.GetPost
type PostUsecaseMockGetPostExpectation struct {
	mock               *PostUsecaseMock
	params             *PostUsecaseMockGetPostParams
	paramPtrs          *PostUsecaseMockGetPostParamPtrs
	expectationOrigins PostUsecaseMockGetPostExpectationOrigins
	results            *PostUsecaseMockGetPostResults
	returnOrigin       string
	Counter            uint64
}

// PostUsecaseMockGetPostParams contains parameters of the PostUsecase.GetPost
type PostUsecaseMockGetPostParams struct {
	ctx context.Context
	id  int64
}

// PostUsecaseMockGetPostParamPtrs contains pointers to parameters of the PostUsecase.GetPost
type PostUsecaseMockGetPostParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// PostUsecaseMockGetPostResults contains results of the PostUsecase.GetPost
type PostUsecaseMockGetPostResults struct {
	p1  model.Post
	err error
}

// PostUsecaseMockGetPostOrigins contains origins of expectations of the PostUsecase.GetPost
type PostUsecaseMockGetPostExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetPost *mPostUsecaseMockGetPost) Optional() *mPostUsecaseMockGetPost {
	mmGetPost.optional = true
	return mmGetPost
}

// Expect sets up expected params for PostUsecase.GetPost
func (mmGetPost *mPostUsecaseMockGetPost) Expect(ctx context.Context, id int64) *mPostUsecaseMockGetPost {
	if mmGetPost.mock.funcGetPost != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Set")
	}

	if mmGetPost.defaultExpectation == nil {
		mmGetPost.defaultExpectation = &PostUsecaseMockGetPostExpectation{}
	}

	if mmGetPost.defaultExpectation.paramPtrs != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by ExpectParams functions")
	}

	mmGetPost.defaultExpectation.params = &PostUsecaseMockGetPostParams{ctx, id}
	mmGetPost.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetPost.expectations {
		if minimock.Equal(e.params, mmGetPost.defaultExpectation.params) {
			mmGetPost.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetPost.defaultExpectation.params)
		}
	}

	return mmGetPost
}

// ExpectCtxParam1 sets up expected param ctx for PostUsecase.GetPost
func (mmGetPost *mPostUsecaseMockGetPost) ExpectCtxParam1(ctx context.Context) *mPostUsecaseMockGetPost {
	if mmGetPost.mock.funcGetPost != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Set")
	}

	if mmGetPost.defaultExpectation == nil {
		mmGetPost.defaultExpectation = &PostUsecaseMockGetPostExpectation{}
	}

	if mmGetPost.defaultExpectation.params != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Expect")
	}

	if mmGetPost.defaultExpectation.paramPtrs == nil {
		mmGetPost.defaultExpectation.paramPtrs = &PostUsecaseMockGetPostParamPtrs{}
	}
	mmGetPost.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetPost.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetPost
}

// ExpectIdParam2 sets up expected param id for PostUsecase.GetPost
func (mmGetPost *mPostUsecaseMockGetPost) ExpectIdParam2(id int64) *mPostUsecaseMockGetPost {
	if mmGetPost.mock.funcGetPost != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Set")
	}

	if mmGetPost.defaultExpectation == nil {
		mmGetPost.defaultExpectation = &PostUsecaseMockGetPostExpectation{}
	}

	if mmGetPost.defaultExpectation.params != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Expect")
	}

	if mmGetPost.defaultExpectation.paramPtrs == nil {
		mmGetPost.defaultExpectation.paramPtrs = &PostUsecaseMockGetPostParamPtrs{}
	}
	mmGetPost.defaultExpectation.paramPtrs.id = &id
	mmGetPost.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetPost
}

// Inspect accepts an inspector function that has same arguments as the PostUsecase.GetPost
func (mmGetPost *mPostUsecaseMockGetPost) Inspect(f func(ctx context.Context, id int64)) *mPostUsecaseMockGetPost {
	if mmGetPost.mock.inspectFuncGetPost != nil {
		mmGetPost.mock.t.Fatalf("Inspect function is already set for PostUsecaseMock.GetPost")
	}

	mmGetPost.mock.inspectFuncGetPost = f

	return mmGetPost
}

// Return sets up results that will be returned by PostUsecase.GetPost
func (mmGetPost *mPostUsecaseMockGetPost) Return(p1 model.Post, err error) *PostUsecaseMock {
	if mmGetPost.mock.funcGetPost != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Set")
	}

	if mmGetPost.defaultExpectation == nil {
		mmGetPost.defaultExpectation = &PostUsecaseMockGetPostExpectation{mock: mmGetPost.mock}
	}
	mmGetPost.defaultExpectation.results = &PostUsecaseMockGetPostResults{p1, err}
	mmGetPost.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetPost.mock
}

// Set uses given function f to mock the PostUsecase.GetPost method
func (mmGetPost *mPostUsecaseMockGetPost) Set(f func(ctx context.Context, id int64) (p1 model.Post, err error)) *PostUsecaseMock {
	if mmGetPost.defaultExpectation != nil {
		mmGetPost.mock.t.Fatalf("Default expectation is already set for the PostUsecase.GetPost method")
	}

	if len(mmGetPost.expectations) > 0 {
		mmGetPost.mock.t.Fatalf("Some expectations are already set for the PostUsecase.GetPost method")
	}

	mmGetPost.mock.funcGetPost = f
	mmGetPost.mock.funcGetPostOrigin = minimock.CallerInfo(1)
	return mmGetPost.mock
}

// When sets expectation for the PostUsecase.GetPost which will trigger the result defined by the following
// Then helper
func (mmGetPost *mPostUsecaseMockGetPost) When(ctx context.Context, id int64) *PostUsecaseMockGetPostExpectation {
	if mmGetPost.mock.funcGetPost != nil {
		mmGetPost.mock.t.Fatalf("PostUsecaseMock.GetPost mock is already set by Set")
	}

	expectation := &PostUsecaseMockGetPostExpectation{
		mock:               mmGetPost.mock,
		params:             &PostUsecaseMockGetPostParams{ctx, id},
		expectationOrigins: PostUsecaseMockGetPostExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetPost.expectations = append(mmGetPost.expectations, expectation)
	return expectation
}

// Then sets up PostUsecase.GetPost return parameters for the expectation previously defined by the When method
func (e *PostUsecaseMockGetPostExpectation) Then(p1 model.Post, err error) *PostUsecaseMock {
	e.results = &PostUsecaseMockGetPostResults{p1, err}
	return e.mock
}

// Times sets number of times PostUsecase.GetPost should be invoked
func (mmGetPost *mPostUsecaseMockGetPost) Times(n uint64) *mPostUsecaseMockGetPost {
	if n == 0 {
		mmGetPost.mock.t.Fatalf("Times of PostUsecaseMock.GetPost mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetPost.expectedInvocations, n)
	mmGetPost.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetPost
}

func (mmGetPost *mPostUsecaseMockGetPost) invocationsDone() bool {
	if len(mmGetPost.expectations) == 0 && mmGetPost.defaultExpectation == nil && mmGetPost.mock.funcGetPost == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetPost.mock.afterGetPostCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetPost.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetPost implements mm_graphql.PostUsecase
func (mmGetPost *PostUsecaseMock) GetPost(ctx context.Context, id int64) (p1 model.Post, err error) {
	mm_atomic.AddUint64(&mmGetPost.beforeGetPostCounter, 1)
	defer mm_atomic.AddUint64(&mmGetPost.afterGetPostCounter, 1)

	mmGetPost.t.Helper()

	if mmGetPost.inspectFuncGetPost != nil {
		mmGetPost.inspectFuncGetPost(ctx, id)
	}

	mm_params := PostUsecaseMockGetPostParams{ctx, id}

	// Record call args
	mmGetPost.GetPostMock.mutex.Lock()
	mmGetPost.GetPostMock.callArgs = append(mmGetPost.GetPostMock.callArgs, &mm_params)
	mmGetPost.GetPostMock.mutex.Unlock()

	for _, e := range mmGetPost.GetPostMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmGetPost.GetPostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetPost.GetPostMock.defaultExpectation.Counter, 1)
		mm_want := mmGetPost.GetPostMock.defaultExpectation.params
		mm_want_ptrs := mmGetPost.GetPostMock.defaultExpectation.paramPtrs

		mm_got := PostUsecaseMockGetPostParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetPost.t.Errorf("PostUsecaseMock.GetPost got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPost.GetPostMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetPost.t.Errorf("PostUsecaseMock.GetPost got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPost.GetPostMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetPost.t.Errorf("PostUsecaseMock.GetPost got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetPost.GetPostMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetPost.GetPostMock.defaultExpectation.results
		if mm_results == nil {
			mmGetPost.t.Fatal("No results are set for the PostUsecaseMock.GetPost")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmGetPost.funcGetPost != nil {
		return mmGetPost.funcGetPost(ctx, id)
	}
	mmGetPost.t.Fatalf("Unexpected call to PostUsecaseMock.GetPost. %v %v", ctx, id)
	return
}

// GetPostAfterCounter returns a count of finished PostUsecaseMock.GetPost invocations
func (mmGetPost *PostUsecaseMock) GetPostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPost.afterGetPostCounter)
}

// GetPostBeforeCounter returns a count of PostUsecaseMock.GetPost invocations
func (mmGetPost *PostUsecaseMock) GetPostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPost.beforeGetPostCounter)
}

// Calls returns a list of arguments used in each call to PostUsecaseMock.GetPost.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetPost *mPostUsecaseMockGetPost) Calls() []*PostUsecaseMockGetPostParams {
	mmGetPost.mutex.RLock()

	argCopy := make([]*PostUsecaseMockGetPostParams, len(mmGetPost.callArgs))
	copy(argCopy, mmGetPost.callArgs)

	mmGetPost.mutex.RUnlock()

	return argCopy
}

// MinimockGetPostDone returns true if the count of the GetPost invocations corresponds
// the number of defined expectations
func (m *PostUsecaseMock) MinimockGetPostDone() bool {
	if m.GetPostMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetPostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetPostMock.invocationsDone()
}

// MinimockGetPostInspect logs each unmet expectation
func (m *PostUsecaseMock) MinimockGetPostInspect() {
	for _, e := range m.GetPostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostUsecaseMock.GetPost at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetPostCounter := mm_atomic.LoadUint64(&m.afterGetPostCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetPostMock.defaultExpectation != nil && afterGetPostCounter < 1 {
		if m.GetPostMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostUsecaseMock.GetPost at\n%s", m.GetPostMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostUsecaseMock.GetPost at\n%s with params: %#v", m.GetPostMock.defaultExpectation.expectationOrigins.origin, *m.GetPostMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetPost != nil && afterGetPostCounter < 1 {
		m.t.Errorf("Expected call to PostUsecaseMock.GetPost at\n%s", m.funcGetPostOrigin)
	}

	if !m.GetPostMock.invocationsDone() && afterGetPostCounter > 0 {
		m.t.Errorf("Expected %d calls to PostUsecaseMock.GetPost at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetPostMock.expectedInvocations), m.GetPostMock.expectedInvocationsOrigin, afterGetPostCounter)
	}
}

type mPostUsecaseMockListPosts struct {
	optional           bool
	mock               *PostUsecaseMock
	defaultExpectation *PostUsecaseMockListPostsExpectation
	expectations       []*PostUsecaseMockListPostsExpectation

	callArgs []*PostUsecaseMockListPostsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PostUsecaseMockListPostsExpectation specifies expectation struct of the PostUsecase.ListPosts
type PostUsecaseMockListPostsExpectation struct {
	mock               *PostUsecaseMock
	params             *PostUsecaseMockListPostsParams
	paramPtrs          *PostUsecaseMockListPostsParamPtrs
	expectationOrigins PostUsecaseMockListPostsExpectationOrigins
	results            *PostUsecaseMockListPostsResults
	returnOrigin       string
	Counter            uint64
}

// PostUsecaseMockListPostsParams contains parameters of the PostUsecase.ListPosts
type PostUsecaseMockListPostsParams struct {
	ctx context.Context
}

// PostUsecaseMockListPostsParamPtrs contains pointers to parameters of the PostUsecase.ListPosts
type PostUsecaseMockListPostsParamPtrs struct {
	ctx *context.Context
}

// PostUsecaseMockListPostsResults contains results of the PostUsecase.ListPosts
type PostUsecaseMockListPostsResults struct {
	pa1 []model.Post
	err error
}

// PostUsecaseMockListPostsOrigins contains origins of expectations of the PostUsecase.ListPosts
type PostUsecaseMockListPostsExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListPosts *mPostUsecaseMockListPosts) Optional() *mPostUsecaseMockListPosts {
	mmListPosts.optional = true
	return mmListPosts
}

// Expect sets up expected params for PostUsecase.ListPosts
func (mmListPosts *mPostUsecaseMockListPosts) Expect(ctx context.Context) *mPostUsecaseMockListPosts {
	if mmListPosts.mock.funcListPosts != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by Set")
	}

	if mmListPosts.defaultExpectation == nil {
		mmListPosts.defaultExpectation = &PostUsecaseMockListPostsExpectation{}
	}

	if mmListPosts.defaultExpectation.paramPtrs != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by ExpectParams functions")
	}

	mmListPosts.defaultExpectation.params = &PostUsecaseMockListPostsParams{ctx}
	mmListPosts.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListPosts.expectations {
		if minimock.Equal(e.params, mmListPosts.defaultExpectation.params) {
			mmListPosts.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListPosts.defaultExpectation.params)
		}
	}

	return mmListPosts
}

// ExpectCtxParam1 sets up expected param ctx for PostUsecase.ListPosts
func (mmListPosts *mPostUsecaseMockListPosts) ExpectCtxParam1(ctx context.Context) *mPostUsecaseMockListPosts {
	if mmListPosts.mock.funcListPosts != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by Set")
	}

	if mmListPosts.defaultExpectation == nil {
		mmListPosts.defaultExpectation = &PostUsecaseMockListPostsExpectation{}
	}

	if mmListPosts.defaultExpectation.params != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by Expect")
	}

	if mmListPosts.defaultExpectation.paramPtrs == nil {
		mmListPosts.defaultExpectation.paramPtrs = &PostUsecaseMockListPostsParamPtrs{}
	}
	mmListPosts.defaultExpectation.paramPtrs.ctx = &ctx
	mmListPosts.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListPosts
}

// Inspect accepts an inspector function that has same arguments as the PostUsecase.ListPosts
func (mmListPosts *mPostUsecaseMockListPosts) Inspect(f func(ctx context.Context)) *mPostUsecaseMockListPosts {
	if mmListPosts.mock.inspectFuncListPosts != nil {
		mmListPosts.mock.t.Fatalf("Inspect function is already set for PostUsecaseMock.ListPosts")
	}

	mmListPosts.mock.inspectFuncListPosts = f

	return mmListPosts
}

// Return sets up results that will be returned by PostUsecase.ListPosts
func (mmListPosts *mPostUsecaseMockListPosts) Return(pa1 []model.Post, err error) *PostUsecaseMock {
	if mmListPosts.mock.funcListPosts != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by Set")
	}

	if mmListPosts.defaultExpectation == nil {
		mmListPosts.defaultExpectation = &PostUsecaseMockListPostsExpectation{mock: mmListPosts.mock}
	}
	mmListPosts.defaultExpectation.results = &PostUsecaseMockListPostsResults{pa1, err}
	mmListPosts.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListPosts.mock
}

// Set uses given function f to mock the PostUsecase.ListPosts method
func (mmListPosts *mPostUsecaseMockListPosts) Set(f func(ctx context.Context) (pa1 []model.Post, err error)) *PostUsecaseMock {
	if mmListPosts.defaultExpectation != nil {
		mmListPosts.mock.t.Fatalf("Default expectation is already set for the PostUsecase.ListPosts method")
	}

	if len(mmListPosts.expectations) > 0 {
		mmListPosts.mock.t.Fatalf("Some expectations are already set for the PostUsecase.ListPosts method")
	}

	mmListPosts.mock.funcListPosts = f
	mmListPosts.mock.funcListPostsOrigin = minimock.CallerInfo(1)
	return mmListPosts.mock
}

// When sets expectation for the PostUsecase.ListPosts which will trigger the result defined by the following
// Then helper
func (mmListPosts *mPostUsecaseMockListPosts) When(ctx context.Context) *PostUsecaseMockListPostsExpectation {
	if mmListPosts.mock.funcListPosts != nil {
		mmListPosts.mock.t.Fatalf("PostUsecaseMock.ListPosts mock is already set by Set")
	}

	expectation := &PostUsecaseMockListPostsExpectation{
		mock:               mmListPosts.mock,
		params:             &PostUsecaseMockListPostsParams{ctx},
		expectationOrigins: PostUsecaseMockListPostsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListPosts.expectations = append(mmListPosts.expectations, expectation)
	return expectation
}

// Then sets up PostUsecase.ListPosts return parameters for the expectation previously defined by the When method
func (e *PostUsecaseMockListPostsExpectation) Then(pa1 []model.Post, err error) *PostUsecaseMock {
	e.results = &PostUsecaseMockListPostsResults{pa1, err}
	return e.mock
}

// Times sets number of times PostUsecase.ListPosts should be invoked
func (mmListPosts *mPostUsecaseMockListPosts) Times(n uint64) *mPostUsecaseMockListPosts {
	if n == 0 {
		mmListPosts.mock.t.Fatalf("Times of PostUsecaseMock.ListPosts mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListPosts.expectedInvocations, n)
	mmListPosts.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListPosts
}

func (mmListPosts *mPostUsecaseMockListPosts) invocationsDone() bool {
	if len(mmListPosts.expectations) == 0 && mmListPosts.defaultExpectation == nil && mmListPosts.mock.funcListPosts == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListPosts.mock.afterListPostsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListPosts.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListPosts implements mm_graphql.PostUsecase
func (mmListPosts *PostUsecaseMock) ListPosts(ctx context.Context) (pa1 []model.Post, err error) {
	mm_atomic.AddUint64(&mmListPosts.beforeListPostsCounter, 1)
	defer mm_atomic.AddUint64(&mmListPosts.afterListPostsCounter, 1)

	mmListPosts.t.Helper()

	if mmListPosts.inspectFuncListPosts != nil {
		mmListPosts.inspectFuncListPosts(ctx)
	}

	mm_params := PostUsecaseMockListPostsParams{ctx}

	// Record call args
	mmListPosts.ListPostsMock.mutex.Lock()
	mmListPosts.ListPostsMock.callArgs = append(mmListPosts.ListPostsMock.callArgs, &mm_params)
	mmListPosts.ListPostsMock.mutex.Unlock()

	for _, e := range mmListPosts.ListPostsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pa1, e.results.err
		}
	}

	if mmListPosts.ListPostsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListPosts.ListPostsMock.defaultExpectation.Counter, 1)
		mm_want := mmListPosts.ListPostsMock.defaultExpectation.params
		mm_want_ptrs := mmListPosts.ListPostsMock.defaultExpectation.paramPtrs

		mm_got := PostUsecaseMockListPostsParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListPosts.t.Errorf("PostUsecaseMock.ListPosts got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListPosts.ListPostsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListPosts.t.Errorf("PostUsecaseMock.ListPosts got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListPosts.ListPostsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListPosts.ListPostsMock.defaultExpectation.results
		if mm_results == nil {
			mmListPosts.t.Fatal("No results are set for the PostUsecaseMock.ListPosts")
		}
		return (*mm_results).pa1, (*mm_results).err
	}
	if mmListPosts.funcListPosts != nil {
		return mmListPosts.funcListPosts(ctx)
	}
	mmListPosts.t.Fatalf("Unexpected call to PostUsecaseMock.ListPosts. %v", ctx)
	return
}

// ListPostsAfterCounter returns a count of finished PostUsecaseMock.ListPosts invocations
func (mmListPosts *PostUsecaseMock) ListPostsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListPosts.afterListPostsCounter)
}

// ListPostsBeforeCounter returns a count of PostUsecaseMock.ListPosts invocations
func (mmListPosts *PostUsecaseMock) ListPostsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListPosts.beforeListPostsCounter)
}

// Calls returns a list of arguments used in each call to PostUsecaseMock.ListPosts.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListPosts *mPostUsecaseMockListPosts) Calls() []*PostUsecaseMockListPostsParams {
	mmListPosts.mutex.RLock()

	argCopy := make([]*PostUsecaseMockListPostsParams, len(mmListPosts.callArgs))
	copy(argCopy, mmListPosts.callArgs)

	mmListPosts.mutex.RUnlock()

	return argCopy
}

// MinimockListPostsDone returns true if the count of the ListPosts invocations corresponds
// the number of defined expectations
func (m *PostUsecaseMock) MinimockListPostsDone() bool {
	if m.ListPostsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListPostsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListPostsMock.invocationsDone()
}

// MinimockListPostsInspect logs each unmet expectation
func (m *PostUsecaseMock) MinimockListPostsInspect() {
	for _, e := range m.ListPostsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PostUsecaseMock.ListPosts at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListPostsCounter := mm_atomic.LoadUint64(&m.afterListPostsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListPostsMock.defaultExpectation != nil && afterListPostsCounter < 1 {
		if m.ListPostsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PostUsecaseMock.ListPosts at\n%s", m.ListPostsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PostUsecaseMock.ListPosts at\n%s with params: %#v", m.ListPostsMock.defaultExpectation.expectationOrigins.origin, *m.ListPostsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListPosts != nil && afterListPostsCounter < 1 {
		m.t.Errorf("Expected call to PostUsecaseMock.ListPosts at\n%s", m.funcListPostsOrigin)
	}

	if !m.ListPostsMock.invocationsDone() && afterListPostsCounter > 0 {
		m.t.Errorf("Expected %d calls to PostUsecaseMock.ListPosts at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListPostsMock.expectedInvocations), m.ListPostsMock.expectedInvocationsOrigin, afterListPostsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PostUsecaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockChangeCommentsAvailabilityInspect()

			m.MinimockCreatePostInspect()

			m.MinimockGetPostInspect()

			m.MinimockListPostsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PostUsecaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PostUsecaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockChangeCommentsAvailabilityDone() &&
		m.MinimockCreatePostDone() &&
		m.MinimockGetPostDone() &&
		m.MinimockListPostsDone()
}
