package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/solumD/ozon-grapql-service/internal/delivery/graphql/generated"
	"github.com/solumD/ozon-grapql-service/internal/model"
	"github.com/solumD/ozon-grapql-service/internal/usecase"
	"github.com/solumD/ozon-grapql-service/internal/utils"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) (*generated.Post, error) {
	post, err := r.postUsecase.CreatePost(ctx, userUUID, title, content, commentsEnabled)
	if err != nil {
		return nil, err
	}

	return toGraphQLPost(post), nil
}

// ChangePostCommentsAvailability is the resolver for the changePostCommentsAvailability field.
func (r *mutationResolver) ChangePostCommentsAvailability(ctx context.Context, postID int, enabled bool) (*generated.Post, error) {
	post, err := r.postUsecase.ChangeCommentsAvailability(ctx, int64(postID), enabled)
	if err != nil {
		return nil, err
	}

	return toGraphQLPost(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, userUUID string, postID int, parentID *int, content string) (*generated.Comment, error) {
	comment, err := r.commentUsecase.CreateComment(ctx, userUUID, int64(postID), utils.ToInt64Ptr(parentID), content)
	if err != nil {
		return nil, err
	}

	return toGraphQLComment(comment), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*generated.Post, error) {
	posts, err := r.postUsecase.ListPosts(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*generated.Post, 0, len(posts))
	for _, post := range posts {
		result = append(result, toGraphQLPost(post))
	}

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*generated.Post, error) {
	post, err := r.postUsecase.GetPost(ctx, int64(id))
	if err != nil {
		return nil, err
	}

	return toGraphQLPost(post), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID int, parentID *int, first *int, after *string) (*generated.CommentConnection, error) {
	filter := model.CommentListFilter{
		PostID:   int64(postID),
		ParentID: utils.ToInt64Ptr(parentID),
	}

	if first != nil {
		filter.First = *first
	}

	if after != nil && *after != "" {
		cursor, err := usecase.DecodeCursor(*after)
		if err != nil {
			return nil, err
		}
		filter.After = &cursor
	}

	connection, err := r.commentUsecase.ListComments(ctx, filter)
	if err != nil {
		return nil, err
	}

	return toGraphQLCommentConnection(connection), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
