package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/solumD/ozon-grapql-service/internal/delivery/graphql/generated"
	"github.com/solumD/ozon-grapql-service/internal/model"
	"github.com/solumD/ozon-grapql-service/internal/usecase"
	"github.com/solumD/ozon-grapql-service/internal/utils"
	"github.com/solumD/ozon-grapql-service/pkg/logger"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, userUUID string, title string, content string, commentsEnabled bool) (*generated.Post, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	post, err := r.postUsecase.CreatePost(ctx, userUUID, title, content, commentsEnabled)
	if err != nil {
		log.Error("failed to create post", logger.Error(err))

		return nil, err
	}

	log.Info("post resolved", logger.Int64("post_id", post.ID))

	return toGraphQLPost(post), nil
}

// ChangePostCommentsAvailability is the resolver for the changePostCommentsAvailability field.
func (r *mutationResolver) ChangePostCommentsAvailability(ctx context.Context, postID int, enabled bool) (*generated.Post, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	post, err := r.postUsecase.ChangeCommentsAvailability(ctx, int64(postID), enabled)
	if err != nil {
		log.Error("failed to change comments availability", logger.Error(err), logger.Int64("post_id", int64(postID)))

		return nil, err
	}

	log.Info("comments availability resolved", logger.Int64("post_id", int64(postID)), logger.Any("enabled", enabled))

	return toGraphQLPost(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, userUUID string, postID int, parentID *int, content string) (*generated.Comment, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	comment, err := r.commentUsecase.CreateComment(ctx, userUUID, int64(postID), utils.ToInt64Ptr(parentID), content)
	if err != nil {
		log.Error("failed to create comment", logger.Error(err), logger.Int64("post_id", int64(postID)))

		return nil, err
	}

	log.Info("comment resolved", logger.Int64("comment_id", comment.ID), logger.Int64("post_id", comment.PostID))

	return toGraphQLComment(comment), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*generated.Post, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	posts, err := r.postUsecase.ListPosts(ctx)
	if err != nil {
		log.Error("failed to list posts", logger.Error(err))

		return nil, err
	}

	result := make([]*generated.Post, 0, len(posts))
	for _, post := range posts {
		result = append(result, toGraphQLPost(post))
	}

	log.Info("posts resolved", logger.Int64("count", int64(len(result))))

	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*generated.Post, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	post, err := r.postUsecase.GetPost(ctx, int64(id))
	if err != nil {
		log.Error("failed to get post", logger.Error(err), logger.Int64("post_id", int64(id)))
		return nil, err
	}

	log.Info("post resolved", logger.Int64("post_id", int64(id)))

	return toGraphQLPost(post), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID int, parentID *int, first *int, after *string) (*generated.CommentConnection, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	filter := model.CommentListFilter{
		PostID:   int64(postID),
		ParentID: utils.ToInt64Ptr(parentID),
	}

	if first != nil {
		filter.First = *first
	}

	if after != nil && *after != "" {
		cursor, err := usecase.DecodeCursor(*after)
		if err != nil {
			log.Error("failed to decode cursor", logger.Error(err))
			return nil, err
		}

		filter.After = &cursor
	}

	connection, err := r.commentUsecase.ListComments(ctx, filter)
	if err != nil {
		log.Error("failed to list comments", logger.Error(err), logger.Int64("post_id", int64(postID)))

		return nil, err
	}

	log.Info("comments resolved", logger.Int64("post_id", int64(postID)), logger.Int64("count", int64(len(connection.Edges))))

	return toGraphQLCommentConnection(connection), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int) (<-chan *generated.Comment, error) {
	fn := utils.GetCurrentFunctionName()
	log := r.log.With(logger.String("fn", fn))

	source := r.commentConsumer.SubscribeToComments(ctx, int64(postID))
	result := make(chan *generated.Comment, 1)

	go func() {
		defer close(result)
		for {
			select {
			case <-ctx.Done():
				log.Info("subscription closed", logger.Int64("post_id", int64(postID)))

				return
			case comment, ok := <-source:
				if !ok {
					return
				}

				mappedComment := toGraphQLComment(comment)
				select {
				case result <- mappedComment:
					log.Info("comment pushed to subscription", logger.Int64("post_id", int64(postID)), logger.Int64("comment_id", comment.ID))
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	log.Info("subscription opened", logger.Int64("post_id", int64(postID)))

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
